### ISSUE TITLE
Individual tag pages should have common link to tag escaping page

### ISSUE THREAD

**Issue by jayrope** [textpattern/textpattern.github.io#102]
The custom field page on the docs lacks complete info on possible values for the escape attribute. EDIT: As etc points out below, this concerns almost all individual tag pages. Therefore i would like to encourage putting a common link to the tag escaping page on all of them.

**Comment by bloatware** [comment]
All currently possible global `escape` values are on [tag escaping](https://docs.textpattern.io/tags/tag-basics/tag-escaping) page. I agree the docs are outdated re global attributes, but this concerns almost all tags.

**Comment by jayrope** [comment]
That makes sense somehow, as you wouldn't need to reprint the same info for all concerned tags. However, in that case the tags' individual pages should link to the tag escaping page. I will rewrite the title of this issue then,
