### ISSUE TITLE
Migrate site to .com suffix

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern.github.io#107]
Need to migrate the domain to docs.textpattern.com from docs.textpattern.io. Including:

- [x] Point DNS of to GitHub
- [x] Change custom domain setting on GitHub Pages site
- [x] Enable HTTPS on GitHub Pages site
- [x] Update links within docs pages to use .com instead of .io
- [x] Check HTML for URLs pointing to .io and amend accordingly
- [ ] Use regular DNS for .io domain (remove Cloudflare) and point to our server (note, this also has an affect on forum so need to stay aware)
- [x] Add AAAA record for IPv6 at Cloudflare
- [x] On go-live, check cross-domain and CSP is allowing access properly

**Comment by philwareham** [comment]
@petecooper I've started the ball rolling on this. I've changed the DNS records on our registrar so that docs.textpattern.com points to GitHub (it was previously pointing to tractor) so please amend your server config accordingly.

Waiting for DNS to propagate before we can go further. I'll also point the old docs.textpattern.io to tractor if you let me know details.

**Comment by petecooper** [comment]
I'll leave `tractor` stuff as-is until DNS is sorted. It looks like .io is using Cloudflare for DNS -- revert to registrar DNS instead?

**Comment by philwareham** [comment]
I've left Cloudflare in place for .io for now, until we have done all the migrations needed. However I have repointed docs.textpattern.io to tractor. Is that the correct thing to do? It'll need to forward to docs.textpattern.com.

Not sure if that could be done purely with DNS or if it needs to go to our server first for a redirect?

**Comment by petecooper** [comment]
If the URL pattern is the same but the TLD has changed, should be easy to do.

Any other special URLs to redirect, or is a straight TLD change?

-- 
Pete Cooper
pete@pragmatika.net
https://pragmatika.net

**Comment by philwareham** [comment]
It's a straight swap of TLD, all other paths are identical.

**Comment by petecooper** [comment]
OK. I'll deal.

**Comment by petecooper** [comment]
If we move the .io DNS away from Cloudflare I (or we) will need to sanity registrar DNS settings since it may take the forum offline if it goes wrong.

Perhaps it's worth postponing the removal of Cloudflare until we're moving the forum, since that's the final piece of the puzzle, as it were.

**Comment by petecooper** [comment]
@philwareham - I've added an AAAA record for IPv6 on `tractor` at Cloudflare, I expect that to jump into life within the hour.
