### ISSUE TITLE
php intl

### ISSUE THREAD

**Issue by wion** [textpattern/textpattern.github.io#109]
In relation to using Bloke's **smd_word_count** plugin, it's necessary to have php's `intl` installed in order for word counts over 1K to show with appropriate numerical notation relative to one's locale, as read from the server. (If I understand all that.)

Most people won't be savvy to this need if their server doesn't already have the module installed. And, presumably, the main reason anyone would use this plugin is because their posts are upwards of 1K words, at least.

So I was first thinking it would be useful to mention the php `intl` situation in the plugin docs, but then realized [this nice suggestion for finding source paths](https://forum.textpattern.io/viewtopic.php?pid=314367#p314367) and such was worthy of general docs too. 

So this a reminder for me to find a good place to work it in.

**Comment by petecooper** [comment]
>I was first thinking it would be useful to mention the php `intl` situation in the plugin docs

Please forgive the rock kicking. If `intl` support is needed for a given plugin, isn't that info for the plugin documentation itself?

**Comment by wion** [comment]
> If `intl` support is needed for a given plugin, isn't that info for the plugin documentation itself?

That part, yes. Agreed.

This part was my real focus...

> then realized [this nice suggestion for finding source paths](https://forum.textpattern.io/viewtopic.php?pid=314367#p314367) and such was worthy of general docs too. 

But now that I look at it again, I think that was a personal dilemma that doesn't come up much for most people, and that doesn't qualify for documentation. Unless @Bloke's suggestion in that forum thread qualifies as an FAQ.

Otherwise, I'm not going to  pursue it, and will close this issue if the FAQ doesn't merit.

**Comment by petecooper** [comment]
`phpinfo()` stuff might be a lot more straightforward if https://github.com/textpattern/textpattern/issues/1425 is accepted. Tagging for completeness.

**Comment by wion** [comment]
Closing. If anyone else thinks it's worth keeping open, feel free to reopen.
