### ISSUE TITLE
Relocating site issue

### ISSUE THREAD

**Issue by NerijusNoreika** [textpattern/textpattern.github.io#110]
Hey,

This is more of an isssue from the user side, I believe, but I hope you can give a bit support on this :) 

My client asked me to relocate his Textpattern site to another server. This is my first time having any exposure to textpattern websites, so I went to read the docs on how to do this.

Found out that the steps needed to be taken are not that different for other sites. Move db, move files, change configuration (and I noticed _CACHE folder so clear cache as well, I guess). I made sure that the PHP version is the same on both servers, i.e. 5.6.

The error I get is 
Fatal error: Call to undefined function create_includes() in /html/textpattern/publish/taghandlers.php(4035) : eval()'d code on line 1

To me it seems that this is a problem with misconfigured path somewhere, but the only place I found where to set it is in textpattern/config.php and there I set it correctly.

Thanks for the help.

**Comment by philwareham** [comment]
@bloke @petecooper @bloatware any thoughts on what's happened here? Thanks. If something missed in our docs, then it'd be good to catch it and document it.

**Comment by bloatware** [comment]
Hi, welcome to txp. What is your Textpattern version? There is no trace of `create_includes()` function in txp core, so either yours is very outdated or it's some plugins effect. Try disabling plugins/php on `Preferences/Publish` admin tab.

**Comment by petecooper** [comment]
>and I noticed _CACHE folder

Hmm. Hacked site? Web server cache files? That's not normal - I wonder if there's something shady in there that's no longer present, and that's a factor in the error.

**Comment by NerijusNoreika** [comment]
Thanks for the quick replies! I don't now know exact version; perhaps there is some constant in a code, where it's written? 

Only clue I found is in index.php - " Copyright (C) 2015 The Textpattern Development Team". So the website is at least 3 years old. :) 

@bloatware I did some grepping around, and found that the  create_includes() function is in /home/_FUNCTION/b_core.functions.php file.

**Comment by petecooper** [comment]
>I did some grepping around, and found that the create_includes() function is in /home/_FUNCTION/b_core.functions.php file.

That's not a Textpattern-native file, so I'm wondering erring toward a) compromised site or b) plugin territory.

@NerijusNoreika - can you go to this URL on the site, please: `/textpattern/index.php?event=diag` This will give you some background info on what we're dealing with version-wise.

**Comment by NerijusNoreika** [comment]
@petecooper It ignores the get argument and just opens up backend login screen.

**Comment by NerijusNoreika** [comment]
@petecooper Thanks for the link, I will write there if I don't resolve this in matter of an hour. 

I do not have the logins at the moment, but I have access to database and it's test only, so I can inject a new password for already existing user. Since it's older version, I tried hashing the password with md5, but it doesn't seem to work. Perhaps there is some internal function I can to make a proper hash?

**Comment by petecooper** [comment]
@NerijusNoreika - try this:

```
INSERT INTO `txp_users` (`user_id`, `name`, `pass`, `RealName`, `email`, `privs`, `last_access`, `nonce`)
VALUES
	(100, 'nerijus', PASSWORD('passwordgoeshere'), 'Nerijus Noreika', 'email@example.com', 1, NOW(), '681327f2f335265698fcf76da8f273bd')
```

Where I have `100`, change that for the next available number from the `txp_users` table. That should make you a user account with a password you set, and the `nonce` will reset when you log in properly.

**Comment by NerijusNoreika** [comment]
Thanks 👍 

Upon loging I get Fatal error: Call to undefined function get_auto_keywords() in /html/textpattern/include/txp_article.php on line 1639

I found the definition on plugin/bb_article_edit_auto_keywords.php This is a plugin, right? Or does Textpattern stores both system plugins and client plugins in the same folder?

So I think there is definitely some problems with include paths. Thanks for the help, I appreciate the time you spend on this issue. I don't want to bother you guys too much. ;) Will either write to the forum of Textpattern or do some digging on my own. Of course if you guys will come up with some additional things to check, will be welcome.

**Comment by bloatware** [comment]
No worries, wish we could help, but the setup definitely seems customized. You can try to search for `name LIKE '%plugin%'` in `txp_prefs` table, disable admin-side plugins and/or check `plugin_cache_dir` path. But if the core has been modified, this might not suffice.

**Comment by petecooper** [comment]
Another aside: if you bundle up all the files (including the cache files) from the old server into a .zip archive, remove the `textpattern/config.php` file and then upload the .zip to https://www.virustotal.com/ does it report back anything suspicious? My gut feeling here is that something suspicious is trying to hide itself.
