### ISSUE TITLE
variable and if_variable tag clarifications

### ISSUE THREAD

**Issue by wion** [textpattern/textpattern.github.io#112]
I can't remember if I ever really knew how to use variables, or I just forgot, but I find them a little confusing now and the docs don't help at all. Maybe I'll try to improve the `variable` and `if_variable` docs, but first I have to understand them. The usual game. So following is what I understand, or think I understand, and what I  don't understand at all. Please someone put me right.

## `variable`

Can be used as a container or single tag.

It has two attributes: `name=""` and `attribute=""`.

The `name` attribute seems straightforward enough. In order to use a variable at all (let alone assign a value to it), it must have a name.

So let's say we want a variable named 'string', and we want to assign a value to that variable equaling 'This is my string'. To do this as a container tag, it would be:

```
<txp:varible name="string">
This is my string.
</txp:variable>
```

How would we use that variable now?  I don't know.

Do assign the same value as a single tag:

```
<txp:varible name="string" value="This is my string." />
```

Again, how would we use that? I don't know.

But I do know that some version of the variable must be put _above_ where the value needs to be output. Example one in the [variable](https://docs.textpattern.com/tags/variable#examples) doc seems to try to explain that idea, but not very well. The example seems like a lot of needless code and doesn't elucidate why the sole instance of the variable tag is at the bottom of it. Beats me.

And apparently you can also do this?

* `<txp:variable name='string' value="" />`
* `<txp:variable name='string' value="0" />`
* `<txp:variable name='string' value="1" />`

But I have no clue what those mean exactly, or why you would use one over the other, and the aforementioned doc doesn't mention any of them in the attributes section, nor any examples given.

So, you can see where some deficiencies are for the those like me who need the detail.

## `if_variable`

Jumping ahead to the `if_variable` tag. Presumably once you have a global variable set to one's liking, you can then call the assigned value in a conditional way, if needed:

```
<txp:if_variable name="string">
  <em><txp:variable name="string" />.</em> It's doing its thing.
</txp:if_varible>
```
Which could also be written using the new tag structure syntax, as:

```
<if::variable name="string">
  <em><txp:variable name="string" /></em> It's doing its thing.
</if::varible>
```

Either way, it would output as:

'_This is my string._ It's doing its thing.'

If someone will help me iron out the kinks in all this, I will commit to augmenting the docs with what I learn. Other pea brains like me should appreciate it.

**Comment by bloatware** [comment]
> How would we use that variable now?

You kinda answer this question in `if_variable` part. Variables are like Forms, you can store any string (even `0` or `1` or empty) inside and output it where needed with `<txp:variable />` tag. Unlike static forms, variables are dynamic, i.e. you can assign them a `value` on the fly. Additionally, you can compare this value against a string with `<txp:if_variable />` tag and act accordingly:
```
<txp:variable name="page" value='<txp:page_url type="pg" />' />
<txp:if_variable name="page" value="1">
    This is the first page.
<txp:else />
    This is the <txp:variable name="page" />th page.
</txp:if_variable>
```

**Comment by philwareham** [comment]
I've added Oleg's example to the variable tag doc, as it's a nice example I think.

**Comment by bloatware** [comment]
You should extend it then to avoid `2th` and `3th` pages.

**Comment by philwareham** [comment]
> You should extend it then to avoid 2th and 3th pages.

Already done!

**Comment by bloatware** [comment]
Ah, great, sorry :-)

**Comment by wion** [comment]
So what does the `value="1"` mean/do in your opening tag. I still don't get what `""`, `"0"`, and `"1"` value values are supposed to do.

**Comment by Bloke** [comment]
Yes, good example, colak.

As you state, from 4.7 we can use the power of `<txp:evaluate>` to short-circuit this particular use case. So, Destry, we now don't need to use variables like that unless we intend to reuse the same content a few times, then it becomes more efficient to do a tag call (article_custom here) once, store its output in a variable and then simply display the variable content multiple times further down the page.

**Comment by wion** [comment]
> You can assign anything you like: 1 is just a convention to mean "something" as opposed to 0 meaning "nothing".

Okay, that kind of starts to make a little sense about the `1` itself. But if `0` means nothing, what would be a reason/example for using it? I've also seen this in tags too: `value=""`. What's the purposes of an empty value?

The rest of the example is still not lucid.

Colak's example is more digestible, perhaps because it's more explicit/verbose. I like it. ;) That's the kind of alternative take that docs need wherever there is a gray zone.

> [Colak] This of course was the pre-4.7 way of doing it but it explains the logic.

Dang. So now that's not applicable anymore?

> [Bloke] As you state, from 4.7 we can use the power of `<txp:evaluate>` to short-circuit this particular use case.

Unfortunately, `evaluate` is another one of those tags that I will probably never fully grok.

> [Bloke] we now don't need to use variables like that unless we intend to reuse the same content a few times,

Do you mean Colak's example? 
In any case, the idea of reusing the same content via variables reminded me of the **section_descriptions** form in the mag, which had a bunch of container variables defined like:

```
<txp:variable name="description-from-the-editor">
An address from the Editor-in-Chief each issue to introduce a current issue's article topics, and to discuss other magazine affairs—as they would concern the interests of readers—that may arise from one issue to another.
</txp:variable>
```

That concept I get. But if I wanted to output that description somewhere, I would just use this,
`<txp:variable name="description-from-the-editor" />`?

`<txp:detour>` The evaluate short-circuiting stuff gets a little esoteric, however. I can appreciate the new power of it for those who know how to wield it, but I think it's prudent to point out there is probably a point where the tag voodoo can be taken too far, defeating their whole purpose of making it easy for non-coders to work with PHP. It's just a different kind of barrier to the masses. Still a great niche tool for the wizards, but then why bother with the themes for soccer mom website owners, if you see what I mean. It's swapping one convenience for another, if you will. I'm not complaining, I'm just offering a word of caution to the future. If things continue as they do, then maybe it becomes necessary to pre-build various kinds of 'modules' that do different common (and slightly uncommon) things so people don't have to figure it out from scratch again and again. `</txp:detour>`

> [Bloke] then it becomes more efficient to do a tag call (article_custom here) once, store its output in a variable and then simply display the variable content multiple times further down the page.

Just to understand if I'm still following... You're talking about Colak's example and not Example 1 from the `variable` doc, which is the 'short-circuited' / new / opposite way, right?

**Comment by wion** [comment]
I think the mag issues situation will be a good exercise for me to think about it. But if the tags can be improved/simplified with the new functionality, that would probably be smart to learn. Perhaps after crawling through that a little more fog will clear.

**Comment by bloatware** [comment]
Actually, in 4.7 `<txp:article(_custom) />` is `else`-aware:
```
<txp:article>
    <txp:title />
<txp:else />
    Nothing here.
</txp:article>
```
An important use case for `<txp:variable />` are counters or lists of all kinds:
```
<txp:article_custom>
<txp:if_first_article>
    <txp:variable name="authors" value='<txp:author title="" />' />
<txp:else />
    <txp:if_article_author name='<txp:variable name="authors" />'><txp:else />
        <txp:variable name="authors" value='<txp:variable name="authors" />,<txp:author title="" />' />
    </txp:if_article_author>
</txp:if_first_article>
</txp:article_custom>

<txp:authors name='<txp:variable name="authors" />' break=", ">
    <txp:author />
</txp:authors >
```

**Comment by wion** [comment]
> [Colak] `<txp:if_variable name="any_name" value="">`
> 
> The `value` here is empty, hence nothing.

 A little confusing on that point. If you're testing for a hit, why tell it to be nothing? Or do you mean something else by 'value'? I'm talking about the `value` attribute's value (`value=""`), which is shown here as empty. Why?

**Comment by wion** [comment]
> An important use case for `<txp:variable />` are counters or lists of all kinds

Okay. I'm expecting both in the periodical issues situation I'm hoping to get established, so again, a good exercise for me, I think.

**Comment by Bloke** [comment]
Yes I was referring to colak's example, sorry for not being clear.

1/0 is just a convention. You could call them 'haz' and 'not-haz' if you prefer. You can still test a variable to see if it contains a zero, or test it to see if it's empty (has no content) via `value=""`.

Variables can be set to any value and can be tested to see if they contain any value previously set.

**Comment by wion** [comment]
> 1/0 is just a convention. You could call them 'haz' and 'not-haz' if you prefer.

Ahhhh... So it's not even an actual fixed attribute value in this case. No wonder the ambiguity. 

> You can still test a variable to see if it contains a zero, or test it to see if it's empty (has no content) via `value=""`.

So you're saying `value="0"` and `value=""` are equivalent? One is the same as the other? Both used to test if conditional is a no hit? Good. This is clearing up.

Another question. If I find this in a mag form, `<txp:variable name="issue" />`, then I should recognize that's being used as an output marker, and the initial definition of that tag will have `value="1"` and is still somewhere higher up the DOM?

**Comment by Bloke** [comment]
> So you're saying value="0" and value="" are equivalent?

In Txp, no. You can test for '0' distinct from 'empty'. This helps if you want to distinguish a counter that hasn't been initialised vs one that had started to be used but hasn't yet been incremented.

With regards a variable tag with no value, yes. That will output the current value assigned to the variable, whatever it may be. Could be a 1, a string, an entire set of articles, anything.

In the case you cite, that tag will output the current issue number read from the current context (URL or article, depending on what you're reading).

**Comment by wion** [comment]
Closing, as Phil had added the example to docs...
https://github.com/textpattern/textpattern.github.io/issues/112#issuecomment-436196222

The rest I'll suffer on my own. ;)

**Comment by wion** [comment]
Closing, as Phil had already added Oleg's example to docs...
https://github.com/textpattern/textpattern.github.io/issues/112#issuecomment-436196222
