### ISSUE TITLE
Switch out Textbook references

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern.github.io#115]
Currently 28 references to http://textbook.textpattern.net - these need replacing with up-to-date equivalents at docs.textpattern.com

**Comment by philwareham** [comment]
OK, make sure they are in the actual live site files - there is a still a fair amount of cruft from the old Wiki that we haven't sifted through and thrown away as yet. Mainly the `faqs` directory and `_recycle` directory need to be audited (and probably most of it chucked).

**Comment by petecooper** [comment]
Yep - doing it now. (y)

**Comment by petecooper** [comment]
Actually these are all in `faqs`, so not live and not generating dead links. Will close and defer for now.
