### ISSUE TITLE
Some articles-are-like-this.md and others_are_like_this.md

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern.github.io#122]
- [x] Decide on `_` or `-` as a word joining character;
- [x] Update style guide so we don't have this happen again;
- [x] Change affected filenames;
- [x] Build out Nginx redirects;

**Comment by Bloke** [comment]
Oooh didn't spot that when I updated the password doc a few minutes ago. You're right.

Looks like the majority of prose-style docs use hyphens so we should probably go with that, _but_ the tags themselves use underscores because that's how the tags are displayed in real life. Might need some exceptions building in, unless we convert everything to underscores.

**Comment by petecooper** [comment]
`txp_tags_should_use_underscores.md`
`articles-should-probably-use-hyphens.md`

That's pretty clear if we note it somewhere, especially since a lot of people will crib from another article in the same directory to build the page scaffold.

**Comment by Bloke** [comment]
> `txp_tags_should_use_underscores.md`
> `articles-should-probably-use-hyphens.md`

Works-for-me.

> a lot of people will crib from another article in the same directory to build the page scaffold.

Yeah, that's what I did with the reset password one. Well, I think it already existed in this case but if it hadn't, I'd have copied what was nearby.

In the `/tags` directory, there are a mixture due to some of the files being tags and some being articles so that's the only place where there might be a little confusion.

**Comment by wion** [comment]
> `txp_tags_should_use_underscores.md`
`articles-should-probably-use-hyphens.md`

As I vaguely recall, that was the decision made in the beginning, though [not clearly detailed](https://github.com/textpattern/textpattern.github.io/blob/master/README.md#filename-url-conventions) (past time to review/revise that page, probably). Tag pages being the only ones with underscores. Made it easy to see when one _was_ a tag page, etc.

**Comment by petecooper** [comment]
Ah, I should've R'd the FM. Thanks for the eyes, @wion.

I will sift through with fresh eyes and see if there are offending articles that don't meet the naming standard, if you're happy to work some README magic, even better. Thank you.

**Comment by philwareham** [comment]
Yes we want to use hyphens for URLs _apart from_ for the name of a Textpattern tag.

So this is correct:

    an-article-about-article_custom-tag-usage

Mainly for readability and (although debatable) SEO improvements (see https://support.google.com/webmasters/answer/76329?hl=en although Google themselves say their algorithms don't punish use of underscore).

**Comment by petecooper** [comment]
Thanks, @philwareham – useful.

**Comment by wion** [comment]
#17

**Comment by wion** [comment]
I've made a pass through the docs tree and these three files in /faqs are the only problems I see:

* managing_clean_urls.md
* resetting_admin_password.md
* troubleshooting_common_xhtml_validation_issues_in_a_textpattern_site.md

Of those, only the second appears to be live in the site.

Which raises a couple of questions:

1. What's the plan with all the FAQ files in the directory that are not live? Is the objective to fix them and make them live? Or merge the info into normal docs?
2. How can I tell if a given live page is linked to from other doc pages, and which ones?
3. Related to No. 2... If I fix the file name on that one live link. Will it break something?

**Comment by wion** [comment]
I've fixed these file names, and corrected the one path in the /faqs index.md.

**Comment by wion** [comment]
The file naming directives are made clear in the [new page template](https://docs.textpattern.com/brand/textpattern-documentation-template). That seems like the most appropriate place. Should I make it redundant in the documentation guidelines too?

**Comment by wion** [comment]
Only thing needing done to close this issue is last item in the head checklist: 'build out nginx redirects'. I don't know anything about that. I'll leave it to Pete.

**Comment by petecooper** [comment]
Done. Closing.
