### ISSUE TITLE
page: User documentation guidelines

### ISSUE THREAD

**Issue by wion** [textpattern/textpattern.github.io#123]
I've added a first draft of a new [user documentation guidelines](https://github.com/textpattern/textpattern.github.io/blob/master/brand/user-documentation-guidelines.md) page, as well as a new docs template page in the same folder (/brand).

I want to run the concept buy editors for review. What I'm doing is working on the brand docs a bit. There will still be the editorial style guide, which I'll be getting to soon. This docs guidelines page is a relative of the editorial guide, but is specifically for documentation and covers a few more topics than an editorial guide would, such as docs collaboration, process, what new material to look for, how to format interface strings, etc.

If the general idea is accepted, I will push a revised (vastly simplified) README file too.

I still have some editing passes to make on the guidelines, and to finish a couple of sections like cross-linking and main text notes sections.

Also some things to focus on:

First, I can't figure out how to get the contents list (toc) nested properly. It's a long one with three or four levels, but for this type of doc, it's kind of needed. I don't know if there's a Markdown problem there, or a GitHub glitch, or if we need to install a [toc plugin](https://github.com/topics/toc)?

Second, bring your attention to the section on [Formatting interface strings](https://docs.textpattern.com/brand/user-documentation-guidelines#formatting-interface-strings). I've thought about this more and propose these new formatting rules depending on what UI string is in question. This doesn't mean a big back-correct chore for such strings already documented; rather, just change them as we go and see them by the new rules. 

In relation to that, the rule about formatting message feedback strings (in the table) mentions some classes for authors to use in those cases. I'm not sure how that works, though. In the Diagnostics doc, for example, I see things used like `All checks passed! {: .alert-block .success}`. What is that syntax?

Then down in the section on [Using notes](https://docs.textpattern.com/brand/user-documentation-guidelines#using-notes). First with regard to reference-mark annotations in tables. I'd like to propose some new CSS that displays a `tfoot` list (when added by an author), that auto-outputs the noted references marks in the order necessary. I've got this set up in my own site, and it works pretty good. This is the general idea:

```
tfoot ol {
	list-style-type:none;
	text-indent:-.75em;
	padding-left:.75em;	
}

tfoot li {margin:.15em 0;}

ol.refmarks {
	list-style-type:none;
	text-indent:-.75em;
	padding-left:.75em;	
}

.refmarks li:before {margin-right:.4em;}

/*single marks*/
.refmarks li:first-child:before {content:'\002a';} /* asterisk */
.refmarks li:nth-of-type(2):before {content:'\2020';} /* dagger */
.refmarks li:nth-of-type(3):before {content:'\2021';} /* double dagger */
.refmarks li:nth-of-type(4):before {content:'\00a7';} /* section sign */
.refmarks li:nth-of-type(5):before {content:'\00b6';} /* pilcrow */
.refmarks li:nth-of-type(6):before {content:'\2016';} /* vertical bars */

/*double marks example, starting with asterisks
.refmarks li:nth-of-type(7):before {content:'\002a\002a';} */
```
I wouldn't worry about the double marks, the first six single marks should be enough nearly all the time.

That's enough to chew on for now. Let me know what everyone thinks.

**Comment by petecooper** [comment]
>If the general idea is accepted, I will push a revised (vastly simplified) README file too.

In https://github.com/textpattern/textpattern or here?

**Comment by wion** [comment]
Here. Between the [documentation guidelines](https://docs.textpattern.com/brand/textpattern-documentation-guidelines), which would provide a bit more depth about contributing to and editing docs, and the [new page template](https://docs.textpattern.com/brand/textpattern-documentation-template) that I also just added, the repo’s ReadMe can be more tailored to a simple repo overview/orientation page instead of the hodge-podge instructions page it currently is. It would retain the info/steps about pull requests though. I have the page edited and ready locally.

**Comment by wion** [comment]
@philwareham,

Fyi, if you add the CSS for reference mark-lists as proposed, the `tfoot` list in the example table in the [Notes in tables](https://docs.textpattern.com/brand/textpattern-documentation-guidelines#notes-in-tables) section should correct itself, depending on the class you choose to use. I can change the class if you want.

**Comment by petecooper** [comment]
>ReadMe can be more tailored to a simple repo overview/orientation page instead of the hodge-podge instructions page it currently is. It would retain the info/steps about pull requests though. I have the page edited and ready locally.

+1 on making the change. Our READMEs generally need some fresh eyeballs. Tagging https://github.com/textpattern/textpattern/issues/1420 for completeness.

**Comment by wion** [comment]
> I can't figure out how to get the contents list (toc) nested properly. 

I have conquered my trouble with the contents (toc) list, so you can ignore that issue. I was using multiple asterisks like in Textile for each level. Doh. 

> In relation to that, Phil, the rule about formatting message feedback strings (in the table) mentions some classes for authors to use in those cases. I'm not sure how that works, though.

I think I have also handled this problem too, by adding a second table in the [Formatting interface strings](https://docs.textpattern.com/brand/textpattern-documentation-guidelines#formatting-interface-strings) section, specifically for system messages. The markup still confuses me, but as long as it works. ;)

Aside from finishing a couple of sections, and giving it all a couple of copy editing passes, I think I'm good, except for the needed CSS on reference marks.

**Comment by Bloke** [comment]
I know it's long, but I vote for leaving the explanatory notes in the _Formatting interface strings_ section as it provides some helpful context should anyone want to know why the choices have been made that way.

This is stellar work, Sir, and long overdue. Thank you.

**Comment by wion** [comment]
Long overdue indeed. Sorry about the hiatus.

I will take two votes for keeping it as, well, keeping it. ;)

I've committed the new README file, as well the index.md, which updates the intro para, long overdue, too, I think.

**Comment by wion** [comment]
Page is now reasonably good. I still haven't given it the witch eye scrutiny, but I think it's safe to say I've ticked this one off.

I will now pass it to Phil about the remaining CSS for the reference-marks.

**Comment by petecooper** [comment]
Great to see you around, @wion!

**Comment by wion** [comment]
Thanks. The wandering soul comes and goes.

**Comment by wion** [comment]
Closing. I will pursue the matter of CSS with Phil [when location for such requests is clarified](https://github.com/textpattern/textpattern.github.io/issues/116#issuecomment-552192443).

**Comment by wion** [comment]
Add guideline about not using software version numbers in documentation (way too hard to maintain across the tree), unless for legacy purposes, and gives examples of how to do it, and what to do in exceptional cases.

**Comment by wion** [comment]
I am now using Z Shell. I don't like the prompt, but 'tis Apple's future.
https://support.apple.com/en-us/HT208050

I mention that page because I note that Apple does not format URIs, paths (including things like ~/etc/shells), file names in documentation. **I like this!** I think this non-format on these elements should be the norm for Txp docs too, and I would update the guideline here...
https://docs.textpattern.com/brand/user-docs-guide#paths-directories-and-file-names

I suggest this for one main reason: It's a lot easier than having to add HTML italic formatting around these elements all the time (i.e. `<i>path</i>`). And remember, that was necessary because frickin' Markdown doesn't have a way to format as italic without adding emphasis too, and emphasis is not what you want on these strings in screen readers. Disaster for anyone relying on that. So no formatting, like Apple goes with, is best, me thinks.

Thumbs up?

**Comment by wion** [comment]
@bloke, I think you're the only one following progress on the guidelines at all, so I'll just direct the above question to you.

Also, there was something else we we're talking about the other day that I was going to add to the guidelines. Do you recall what it was? Besides the two things noted in the previous two comments here.

**Comment by Bloke** [comment]
Can't recall, sorry. It might have been to do with the italics on filenames anyway. Had a quick scan but couldn't find the thread. If I do, I'll let you know.

**Comment by wion** [comment]
Section added to meet https://github.com/textpattern/textpattern/issues/1431.
