### ISSUE TITLE
page: Themes panel

### ISSUE THREAD

**Issue by wion** [textpattern/textpattern.github.io#130]
https://docs.textpattern.com/administration/themes-panel

The Themes panel is a good example of having a pophelp that's out of balance with the docs page.

Here's the pophelp on the panel header:

> Introduction to Themes
>
> A Textpattern theme is a collection of Pages, Forms and Stylesheets. Themes allow you to logically separate your site assets into groups for ease of identification, or sharing with others. The act of creating or importing a Theme, and any assets it contains, does not have any impact on your existing site. You are free to edit or modify any asset that is not associated with a Section of your site, and it will not affect the site itself.
>
> To edit assets in a theme, visit the Pages, Forms or Styles panel and use the dropdown selector to choose the theme upon which you wish to work. The theme you are working on is remembered throughout the administration area, allowing you to jump between asset types quickly and easily. It is referred to as your working theme.
Previewing theme assets
>
> All the while you are working on a theme, Textpattern will permit you (and only you) to preview the assets in that theme. Just visit the public website while you are still logged in to the administration area. Provided Textpattern can locate an asset with the same name as the one that is already assigned to the public Section of the site you are visiting, it will show you what your site will look like by using the working theme as a preview.
>
> This allows you to rapidly see changes to your theme‘s assets and continue to alter items prior to making them available to the public. At any time, switching your working theme from the administration area will allow you to preview those assets.
>
>When you are satisfied with the results, assign assets from any theme(s) to one or more Sections of your site. This will make those assets live, and visible to any site visitors.
Exporting and importing
>
>Themes may be shared with the community. Select one or more themes via the checkboxes and use the multi-edit tool‘s export option to export the theme assets to disk. Each theme is located in its own sub-directory, beneath the directory defined in your Theme directory preference setting (default: themes).
>
> Once there, you can package it up and distribute it. Others may unpackage themes into their own directory and use the import tool to bring the assets into their database. From there, they may switch to the theme and use that as their working theme, permitting preview of assets within the site and, ultimately, assignment of assets to Sections as described above.
>
> The ability to export themes also allows you to make a backup, edit asset contents on disk in your text editor and/or apply version control to them. Remember: there is no link between your public site and the disk-based version of your assets. In order for visitors to see the changes, you must first import alterations into your database and ensure that one or more Sections are using the assets from the theme.

Yipes! That's a lot of content for an inline pophelp; nearly as much as what's on the user doc page itself. If the pophelp box has to scroll, the recommended max volume of information has probably been exceeded by quite a bit. And isn't that putting a lot on the shoulders of translators? 

Most volume of help content should be in the user doc, when volume is needed, where it's easier for people to revise and edit.

Are there a lot of big pophelps like that floating around? If so, we might want to think about toning those down, and make better use of user docs. Pophelps should be on individual features in a panel, explaining individual items in bite-sized chunks; not on panel headers and over viewing the entire panel, imo.

**Comment by Bloke** [comment]
It is big. There's also a 'What is a Form' entry on the Forms panel.

**Comment by wion** [comment]
If there are no objections, I think I can take this on,  and kill three birds with one attempt:

1. Reduce the 'Themes panel' doc to features focus only.
2. Write a relatively thorough Theme creation tutorial out of the 'Front-end themes' doc (to be re-titled), addressing issue #128.
3. Whittle down the pophelp on the panel doc by parsing the good bits there into docs context and keeping only what's needed.

Assign me up if that's good sounding. (I'm already started anyway.)

**Comment by wion** [comment]
As far as I'm concerned, the themes panel doc is obsolete against this new one...
https://docs.textpattern.com/build/themes-creating-using-and-sharing

Closing issue and won't be looking at the themes panel doc again except when it comes time to axe it.
