### ISSUE TITLE
proposed: Revision on the universal page-ending info/notice

### ISSUE THREAD

**Issue by wion** [textpattern/textpattern.github.io#134]
I've tried looking for where this is managed, but don't find it. Anyway, the info box currently reads:

> See something wrong in this document? Outdated info, a broken link, faulty code example, or whatever? Please open an issue and we’ll investigate.

I propose an upgrade to:

> If you see (or hear through your screen-reader) any kind of problem with this page's construction or content (outdated information, typos, broken links, false code examples, or whatever), [open an issue](https://github.com/textpattern/textpattern.github.io/issues/new?assignees=&labels=&template=discuss-existing-page.md&title=page%3A+) to have it sorted. Or [have a go at it](https://github.com/textpattern/textpattern.github.io/blob/master/README.md) yourself. :)

Note that's a new issue link, direct to the 'Discuss existing page' template.

Yes, it's unlikely anyone relying on screen readers is using Textpattern software (do we know of anyone?), but at least it shows we are aware, and I genuinely would like to know if any formatting rules I've pushed in guidelines are breaking rules with screen-readers, without me having to figure that out on my own.

**Comment by philwareham** [comment]
Sounds good to me.

**Comment by wion** [comment]
You win the honor. ;)

**Comment by philwareham** [comment]
OK, done that! Please close the issue if you are happy with it.

**Comment by wion** [comment]
Looks good. I'm not crazy about the smiley, after all, but I'll leave that to your discretion.

**Comment by philwareham** [comment]
Do you just want is as :) instead?

**Comment by wion** [comment]
That was the idea, but I don't know now. Maybe it's better without. Clean. No matter.

**Comment by philwareham** [comment]
I think it needs one or the other as a sweetener - otherwise it seems a bit curt to say 'maybe do it yourself'...?!

**Comment by wion** [comment]
Maybe. Plain text style, then, if at all. The smilies are just to comics-looking.

'Or have a go at it yourself' is meant more as an open invitation to get involved. But maybe from a British perspective it comes across as passing the buck? lol Good to know.

**Comment by Bloke** [comment]
Late to the party, sorry, but wouldn't this be more succinct:

> If you notice any kind of problem with this page's construction or content...

Do we really need to spell out the screen reader aspect?

**Comment by wion** [comment]
Yep, that wraps it together nicely. And this is even cleaner...

> If you notice any problem with this page's . . .
