### ISSUE TITLE
meta: docs on GitHub Pages, and associated URL redirects

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern.github.io#138]
It just dawned on me, when setting up a URL redirect on our server, that `docs.textpattern.com` is hosted at GitHub Pages, and so the redirect cannot be done with Nginx, since it's not handled by Nginx. Hmm.

Few options here: we could let the old URLs languish and the search engines pick up the new ones, or we could self host the docs and have Nginx do the redirects properly (has the added benefit of some traffic stats), or we could investigate a GitHub Pages redirect as part of the build process (probably easiest in terms of work), or something else.

@philwareham - you know much more than I do about how GitHub Pages works, is a redirect doable with the current setup?

**Comment by philwareham** [comment]
Erm... https://github.com/orgs/textpattern/teams/documentation-team/discussions/11?from_comment=2#discussion-11-comment-2 😉

**Comment by philwareham** [comment]
Basically there's no good way of doing redirects on GitHub Pages, apart from having a clunky HTML file with a meta refresh:

```
<!DOCTYPE html>
<html lang="en-GB-oxendict">
<head>
    <meta charset="utf-8">
    <meta name="robots" content="noindex, follow">
    <meta http-equiv="refresh" content="0;url=THE_NEW_URL">       
    <link rel="canonical" href="THE_NEW_URL">                     
</head>                                                                                                                                                                   
<body>                                                                      
        <h1>The page been moved to <a href="THE_NEW_URL">THE_NEW_URL</a></h1>                                                                   
</body>                                                                     
</html>
```

**Comment by petecooper** [comment]
>Erm...

My bad, missed that!

Leave this with me, I'll ponder solutions.

**Comment by philwareham** [comment]
This will be negated when we move to self-hosted Jekyll. Closing as this is covered by issue #162.
