### ISSUE TITLE
page: Author prefixes and registration

### ISSUE THREAD

**Issue by wion** [textpattern/textpattern.github.io#139]
Proposed/new title and URL: 'Author prefixes and registration'
https://docs.textpattern.com/brand/author-prefixes-and-registration

Formerly: 'Plugin developer prefixes'
https://docs.textpattern.com/development/plugin-developer-prefixes

## Situation

Discussion in forum about how to handle theme author prefixes lead to using this page to register/record them, so not conflicting with running list of prefixes already registered. However, the page is entirely oriented around prefixes as a 'developer' thing. Title, content, associated linked pages... It all needs revised. Context needs edited to communicate the prefixes more generally.

Note the proposed new title above. Since this is a more universal use of the prefixes now, and since the page and file does need to be re-labeled, I'd suggest putting the file in /brand directory, because that's essentially what it has become, a community guidelines doc for collaboration.

## Checklist

To catch all the linked pages.

- [x] https://docs.textpattern.com/development/plugin-developer-prefixes
- [x] https://docs.textpattern.com/development/ (index page; section #register-your-plugin-developer-prefix)
- [x] https://docs.textpattern.com/themes/themes-a-complete-walk-through

Not sure what else.

## Homepage link

Since this is no longer just a plugins dev thing, maybe this page needs moved from the /developer directory entirely, perhaps to /brand? This is somewhat brand territory, after all. Working with it. ;)

Then a link to the **Author prefixes and registration** could go under the Themes and Developer lists on the docs homepage lists?

**Comment by wion** [comment]
Claiming the prefix 'dry' (D___ry). Seems a nice opposite of wet. ;)

**Comment by Bloke** [comment]
Argh, Fail on my part. I added your prefix without claiming the doc first. *slaps hand*

**Comment by wion** [comment]
No worries. We should change the name, though, to start a new working link.

**Comment by wion** [comment]
Maybe that needs a checklist to catch all the associated linked pages too. :{

**Comment by wion** [comment]
Head post updated with latest noodling.

**Comment by wion** [comment]
Page revised, re-titled and moved under /brand. All links to  page from user docs (that I could find) also updated.

When the Plugins website is done and a inventory has been made on valid/circulating plugins, an audit of that prefixes list will be warranted. I suspect there's a lot of cruft and unused prefixes indicated there as taken.
