### ISSUE TITLE
Search box on main page works not

### ISSUE THREAD

**Issue by wion** [textpattern/textpattern.github.io#140]
https://docs.textpattern.com

Tried using the following search terms: 'version', '4.7', 'sections', 'sections panel', 'administration'... Got _zero_ results in every case. There must be something wrong there, which makes that oversized search box in user documentation a little comical.

**Comment by bloatware** [comment]
`139 document(s) found matching your search request "version".` Is your browser allowed to connect to `code.jquery.com`?

**Comment by philwareham** [comment]
Can’t reproduce here. Get results for those searches. FYI the Jekyll search is JavaScript so it won’t work if you’ve disabled JS in your browser. Otherwise I’m stumped as to why you are not getting results and I am.

**Comment by wion** [comment]
Doh! Sorry. Amateur hour.
