### ISSUE TITLE
page: Naming conventions for (theme designers)

### ISSUE THREAD

**Issue by wion** [textpattern/textpattern.github.io#142]
The page in question...
https://github.com/textpattern/textpattern.github.io/blob/master/themes/naming-conventions-for-template-authors.md

## The question/problem

Is this page needed? Will [this treatment of theme naming suffice](https://docs.textpattern.com/build/themes-creating-using-and-sharing#author-prefix-and-registration)?

## Proposal

If we can axe this page, let's do.

**Comment by wion** [comment]
#139

**Comment by Bloke** [comment]
Don't think we need this. The naming conventions and folder structure are nailed down now, and any exceptions (such as spaces in filenames, them name conventions and stuff like that) are covered in the Theme doc you wrote. Shall we stick this in the recycle bin?

**Comment by wion** [comment]
Has been stuck and stricken.
