### ISSUE TITLE
page: Installing the software

### ISSUE THREAD

**Issue by Bloke** [textpattern/textpattern.github.io#145]
Old doc and location
https://docs.textpattern.com/installation/

New doc and location...
https://docs.textpattern.com/setup/installing-the-software

### The question/problem

This is the index page of the installation directory. Should it really have such an arduous step-by-step guide?

### Proposal

1. Move 'installation/index.md' content to 'installation/detailed-installation-guide.md' page and revise it a little.
2. Rename the existing 'installing-textpattern.md' as 'quick-installation-guide.md' which contains the abridged 'new' and 'upgrade' sections as it does now.
3. Make the 'installation/index.md' page a jump-off/landing page for all things instally. Just a glorified TOC, really with a little intro para. It won't be linked from the main index page - that will list the direct links to each specific installation doc in the directory - but the index.md content will appear if anyone sets the URL directly, and we can use it as a back-link from deeper installation pages, instead of directing people to the front page each time.

Thoughts?

**Comment by wion** [comment]
Yep. Sounds like a good place to start on that; gets it sorted better. I had recognized that too. Just had other things to do before ticketing it. I might have had some role to play in the crime years ago, but can't remember.

The 'detailed' idea of a installation doc is a tad overkill, IMO, and we should lose that word; especially when the few steps that come in the package ReadMe file is perfectly fine 99% of the time.  Ideally we'd lean on those simple install instructions that ship with core (the 'quick' guide, if you will), and even point to that file from the index list you mention as **Installation quick-guide**, or similar? Then _one_ additional user doc, perhaps a bit more elaborated but not excessively 'detailed'. Maybe:  **Installation: From download to first log in**; throw a couple of key images in it. That should be all that's ever needed in user docs.

We could even make that a concise two part doc, **Complete installation and update instructions**, or whatever, and tie two old docs together.

But in the meantime, yes, the proposal is a good start to get it sorted for a while, in case it can't be tended to right away. Sometimes these step-wise progressions are more efficient/helpful than sudden, radical revisions of the tree.

**Comment by Bloke** [comment]
I'm fine with using the quick installation as the go-to doc in conjunction with the README.

The detailed one does have some niceties though - the list of what each folder is for is a useful 'overview' for people that care where stuff is stored, and what can be omitted. Though a table would take up way less space and be easier to digest, if we choose to keep that. If not, would that info be more useful to put elsewhere before it gets ditched?

Good idea about losing the 'detailed' moniker.

I think I'm more inclined to go with a 'Complete' guide split into sections. Less maintenance overhead and the TOC allows people to jump to the level they require.

**Comment by wion** [comment]
Yeah, if the 'detailed' one has some nice things, by all means pluck those pieces out for recycling. Make a 'medium' version; not readme-quick,  not overly detailed, but 'juuuuuuust right', said Goldilocks.

**Comment by wion** [comment]
But, yeah, better to start with detailed. It can always be refined down the road if warranted.

**Comment by wion** [comment]
Note I changed file name to use 'verb and verb', which is more appropriate than 'noun and verb'.

**Comment by wion** [comment]
Note I changed file name to use 'verb and verb', which is more appropriate than 'noun and verb'.

**Comment by wion** [comment]
Continuing from [here](https://github.com/textpattern/textpattern.github.io/issues/148#issuecomment-562993980) so not to get off-topic in that issue.

Normally I'd say it's fine to combine installing and upgrading. But the doc seems to have both quick and detailed versions of each one. That essentially makes four different instructions in one doc, which is probably overloading it. What I was suggesting earlier up is to not write 'quick' guides in user docs at all. Just point to the [readme.txt](https://github.com/textpattern/textpattern/blob/master/README.txt), for example:

* [Installing and upgrading](https://docs.textpattern.com/setup/installing-and-upgrading)
  ** [Quick guide reminders](https://github.com/textpattern/textpattern/blob/master/README.txt)
* Configuration essentials
* Collaborative roles and rights
* . . .

Otherwise, it should be three different docs an four unique links:

* [Installing the software](https://docs.textpattern.com/setup/installing-and-upgrading)
  ** [Quick guide for installing](https://github.com/textpattern/textpattern/blob/dev/README.md#install-textpattern)
* Upgrading the installation
  ** [Quick guide for updating](https://github.com/textpattern/textpattern/blob/dev/README.md#upgrade-textpattern)
* Configuration essentials
* Collaborative roles and rights
* . . .

Btw, it seems to me if we link to the .txt file (and even if not), as in the first example, it should use explicit numbering (not asterisks) for ordered lists. Or, if we link to the individual sections of the .md file, in the second example, those sections should be filled out, since that page is more readable. 

Also, [regarding paths and file names](https://docs.textpattern.com/brand/user-docs-guide#paths-directories-and-file-names). They are not code. :)

**Comment by wion** [comment]
Ever notice how confusing it is to get 'upgrading' and 'updating' straight? My brain thinks the former and my fingers type the latter. Always have to go back and correct. They seem rather synonymous, but 'upgrading' is the better word, yes?

**Comment by Bloke** [comment]
I'm easy either way. If you think we need dedicated quick-guides, that's cool, we can split them out. If you think the README is good enough, we can hack out the first two sections, no problem.

As for upgrading/updating, I used the terms interchangeably. My reasoning? Search. What I didn't want to happen was this:

_updating textpattern_ : no search results
_upgrading textpattern_ : produces results

Pushing our nomenclature onto people is fine and good for consistency, but from a user perspective, it's frustrating to have to innately 'know' jargon terminology in order to find stuff. If there's a better way to do this so a search for either term returns the correct page, I'm all ears (you'll notice that the meta description uses one term when the title uses the other, for example).

And on that note, why does the frontmatter not render correctly on this doc? It shows up as a table in all other pages, but not here, even though I copied and pasted the formatting and changed just the words. What am I missing?

Note to self: try and embed the many house style rules in my head somehow. bold, italic, bold-italic, quoted, ... Argh!

**Comment by wion** [comment]
We need to remember something important about editing in general. There is the drafting, and there is the editing, and the two tasks should rarely be done by one person on the same file. It's impossible to get everything that way unless you comb over the file 20 times and I don't expect you to do that. Just get the file written/structured to completion information wise under the 'drafting' label, that pass it to me for editing when done. I know you have better things to do.

**Comment by wion** [comment]
> (you'll notice that the meta description uses one term when the title uses the other, for example)

This kind of intentional strategy needs to get written into the docs guidelines or else it's pointless in a collaborative situation. We can't read each other minds. So if you can articulate a use-case plan around terminology use for search benefit, do share, and we'll get it into the guide ASAP for my benefit.

**Comment by wion** [comment]
On the other hand, if every doc is listed on the homepage under very clear titles (excepting all the tag pages), is there a need for a complicated search terminology strategy? Maybe not. But it can't hurt to have an alternative term or two used in the descriptions. Let's play it like that. I'll update the docs guidelines.

**Comment by wion** [comment]
> I'm easy either way. If you think we need dedicated quick-guides, that's cool, we can split them out. If you think the README is good enough, we can hack out the first two sections, no problem.

I'm aiming for what is the least redundant; thus the most focused. Following are the three sensible options, IMO...

One doc with no quick guide sections:

* [Installing and upgrading](https://docs.textpattern.com/setup/installing-and-upgrading)
* Configuration essentials
* Collaborative roles and rights
* . . .

Two docs with quick guide link outs:

* [Installing the software](/setup/installing-the-software)
  * [Quick guide for installing](https://github.com/textpattern/textpattern/blob/dev/README.md#install-textpattern)
* [Upgrading the installation](/setup/upgrading-the-installation)
  * [Quick guide for upgrading](https://github.com/textpattern/textpattern/blob/dev/README.md#upgrade-textpattern)
* Configuration essentials
* Collaborative roles and rights
* . . .

Two docs with no quick guide link outs:

* [Installing the software](/setup/installing-the-software)
* [Upgrading the installation](/setup/upgrading-the-installation)
* Configuration essentials
* Collaborative roles and rights
* . . .

When I see it like that, the third option looks best to me, and probably offers the best search strategy too.

**Comment by Bloke** [comment]
Third option works for me. I'll split it out, no problem. We'll just have to duplicate and tweak the 'file table' at the bottom, or refactor that concept into the body copy. I'll figure it out.

**Comment by Bloke** [comment]
> it can't hurt to have an alternative term or two used in the descriptions. Let's play it like that. I'll update the docs guidelines.

Cool, thanks. I agree there shouldn't be any _need_ for such strategies, but the JavaScript-powered search in Jekyll is so sucky, it requires as much help as it can get. Presumably it searches _within_ the frontmatter so it can pick up alternative terms in the description? Must admit I haven't actually tried that.

It's always frustrating when search fails for the stupidest things:

_meaningful labour_ : no search results
_meaningful labor_ : lots of results

:)

**Comment by Bloke** [comment]
Okay, I've split them out and linked to them from index2. Not proofread or anything, but you're right the file tree and def lists are much better.

We could probably do with better links to the readme instead of sending people to a place where they need to perform a second click.

**Comment by wion** [comment]
> Not proofread or anything

As your lawyer and editor, I advise you to pass assignment to me.

> the file tree and def lists are much better

Yep.

> We could probably do with better links to the readme instead of sending people to a place where they need to perform a second click.

Yeah, that's why I was saying earlier, we need to either fill out those section in the .md file that you linked to, or link to the actual .txt file that you named but didn't link to. ;)

But now that I'm reminded of this in the tops of the main docs...

> If you’re familiar with installing CMS software and prefer a quick guide, see the README.txt file that’s included in the download package.

We could remove the two second-level links from the homepage list. Let each main doc provide the external links in the intro para like that. Makes for cleaner lists, and is more focused on what we are actually maintaining in this platform.

Just a thought.

**Comment by Bloke** [comment]
Axed from index2.

**Comment by wion** [comment]
There are also these 'quick' install/upgrade resources, as I just rediscovered...
https://textpattern.com/start

**Comment by Bloke** [comment]
Aye, maybe that's a better place to link than the README. Let's consider it when we take a look at what links where and try to consolidate as much of this duplication as possible.

**Comment by wion** [comment]
There's no breadcrumb trail at the top of this file on front-end, only the big search box. Should be the other way around, I think, but I can't figure out what the problem is. All the other files are okay.

**Comment by Bloke** [comment]
Yeah, the frontmatter is screwed up but I don't know why. @philwareham Any ideas?

**Comment by wion** [comment]
I figured it out. Yaml doesn't like having colons in the metadata values. I'm not sure if you can set the values in quotation marks or something, but I just changed the colon to an em dash and it worked.

Same problem in the themes doc too. We can still use them in main titles, for example, but just not in the metadata.

**Comment by wion** [comment]
> I'm not sure if you can set the values in quotation marks or something

Yes, putting straight double quotation marks around the value will enable  keeping a colon. Works on theme doc. Otherwise is looks dumb in the breadcrumb trail with a em dash.

**Comment by wion** [comment]
@Bloke when you're done drafting (this or any other page). Remove label and change assignment to me for editing review (i.e. the second pair of eyes pass on typos, formatting, etc.).

**Comment by Bloke** [comment]
Sorry, forgot. Done.
