### ISSUE TITLE
page: Installing on an Nginx weserver

### ISSUE THREAD

**Issue by Bloke** [textpattern/textpattern.github.io#147]
### Absolute URL of front-end page

https://docs.textpattern.com/setup/installing-on-an-nginx-webserver

### The question/problem

Is there anything in this file that we don't have already in https://docs.textpattern.com/setup/configuring-a-web-server-for-textpattern? If so, can we migrate the content to this doc and then remove the Nginx-specific doc?

**Comment by petecooper** [comment]
Yep, it's tagged in https://github.com/textpattern/textpattern.github.io/issues/76 - I will find time this week to merge any useful stuff from the former into the latter.

**Comment by Bloke** [comment]
Ooops, sorry. Didn't spot that one. Feel free to close this.
