### ISSUE TITLE
page: global attributes and cross-referencing

### ISSUE THREAD

**Issue by Bloke** [textpattern/textpattern.github.io#157]
### Absolute URL of front-end page

https://docs.textpattern.com/tags/tag-attributes-cross-reference#breakby

### The question/problem

Since 4.7.0, certain attributes of ours have been _global_ - available to every tag. This makes a bit of a mockery of including them on the attribute cross-reference page, since we'd have to list every tag there.

But, although the tags are global, they are _not universally the same_. So although the attribute might be available if you add it to any tag, it will render something or perform that action, but tags (or plugin tags) that already handle that attribute themselves will still continue to do so and thus _won't_ benefit from the global nature of the attribute.

[EDIT: example removed, as I misunderstood something]

So that leaves us in a bit of a pickle.

## Option 1
Do we show on the attribute cross-reference _only_ the global attributes that are not handled globally?!? i.e. the exceptions?

## Option 2
Do we introduce a single new page that goes into more detail about global attributes and lists each one, and gives examples?

## Option 3
Do we do what we've done for the [escape attribute](https://docs.textpattern.com/tags/tag-basics/tag-escaping) and give each global attribute its own page? That way, we can link to that page from the common-atts include page and be done with it, describing the various global options and then listing the exceptions and how they differ.

In short, what do we do and how to we handle documenting global attributes and their exceptions? I'm inclined to go with option 3.

Further, do we add global attributes like 'escape' to every tag page, since it will respond on all tags, but some may behave differently? And do they go under their own subheading? So we'd have for each tag page:

## Attributes

_list of main attributes_

### Common presentational attributes

_list of common presentational attributes_

### Global attributes

_list of global attributes like escape, trim, etc_

---
If so, I'll move the escape attribute out of the common-atts.html include file and put it in its own file along with the other global atts. Perhaps we don't list global attributes at all on tag pages, and just have a single link to a global attributes page which houses all of them, with examples. Rather like the escape doc does now.

**Comment by wion** [comment]
Can't say I'm following this in full clarity, but if the volume of matter of each attribute warrants a page, that's probably wise in this case.

Btw, should that be the direction, I would have renamed the 'Tag escaping' page (file name) to either just _escape.md_, or perhaps _escape-attribute.md_, and that becomes your pattern for them all.

I suppose this would warrant a _/tags/attributes/_ directory, which again, makes it shame we can't do this:

* tags
  * attributes (all attributes pages)
  * reference (all tags pages)
  * shortcodes (all examples)
  * index.md (as directory contents list)

But, as long as we can remove all other _.md_ files from the _/tags_ directory, so it's only tag page files and other subdirectories, that's the next best thing. It's when we start mixing tag page files with other files in the same directory that it gets annoying.

**Comment by wion** [comment]
Which reminds me, what are we to do with the tag category pages? Something like this..

* tags
  * attributes (all attributes pages)
  * categories (all category pages)
  * shortcodes (all examples)
  * index.md (as directory contents list)
  * tag-page.md
  * tag-page2.md
  * . . .

**Comment by Bloke** [comment]
As far as I'm, concerned, when/if we switch over to a single learning-tags page, all the other .md files in the tag-basics page can go to the recycle bin. They're all encompassed in the one doc. I think we can get away with the tag escaping in the flow of the page, but if we need to split that bit out to a separate doc, that's cool.

**Comment by wion** [comment]
All the tag basics pages are in a subdirectory, _/tag-basics_, so their not really the problem (though I'd rename to just 'basics') when it comes to mixing with tag page files. The various category pages, OTOH, like _conditional-tags.md_, _article-tags_, and so on are mixed with tag pages, currently.

**Comment by Bloke** [comment]
Regarding the category pages, I'd like to revisit those as they're butt ugly and not very eye-scannable.

I think we should  move the subcategory pages out of the /tags directory into their own directory. But, there's an argument to be had for making the page itself an include and making it cleverer by having just one doc and passing in a variable to indicate which category they belong. I'm getting the hang of that now in Liquid and think it's doable.

**Comment by Bloke** [comment]
Lemme just fix up the global-atts page, then I'll look at refactoring the subcats to remove those files for the /tags directory.

**Comment by Bloke** [comment]
Okay, I've gone with a simplified structure to this. We should list global attributes on every tag page, because they're attributes after all and need documenting as such. To that end, I've created a 'global-atts.html' include file which should be called into all tag pages after the 'common-atts.html' (if that file's applicable) or after the attributes list (if any).

It lists all the global attributes, their allowable values, and permits you to override what is shown as a default value by passing in the name of the attribute and an override value. For example, on "section_list":https://docs.textpattern.com/tags/section_list we have:

```
{% include global-atts.html class="tag name or unset" %}
```

to override the class attribute defaults. All other (omitted) globals passed into the include will take on their pre-defined defaults (mostly 'unset').

**Comment by Bloke** [comment]
There is one slightly crap thing about using includes, btw. The subheading in `<h3>` tags in the includes, aren't picked up by the automatic TOC. Presumably, this is because of the rendering order of Liquid/Jekyll pages and it only scans the current page for headings.

If we can live with these subheadings not appearing in the TOC, fine. If we think we need them, we'll have to hard-code the headings in each tag page, and remove them from the includes. More work, but hopefully only a one-off.

Thoughts?

**Comment by Bloke** [comment]
Bump @wion Can we live without the common and global attributes headings appearing in the TOC? See comment immediately above.

**Comment by Bloke** [comment]
Renamed the include files to group them better in the files list:

```
{% include atts-common.html %}
{% include atts-global.html %}
```
In addition, I've added an optional parameter: `preamble="0"` will silence the heading and introductory paragraph, returning _only_ the list of attributes. This makes it usable in contexts such as the [learning tags doc](https://docs.textpattern.com/tags/learning/#global-attributes-list) so we can just switch off the preamble when including that file, supply our own in the doc itself and benefit from having a single place where all global attributes are sourced.

**Comment by wion** [comment]
> Bump @wion Can we live without the common and global attributes headings appearing in the TOC? See comment immediately above.

@Bloke, Sorry. I completely missed this. Is this still a question? It looks like maybe you addressed it with the `preamble="0"` thing, but I'm still hazy on what the original problem was.

I have not looked at tag pages, or been able to open the atts-global.html yet (which I'm sure is as nifty as Jekyll will allow). I'm rather assuming Phil is paying better attention to your advancements there since he is more concerned with the construction of tag pages than I am.

As for the Kramdown ToC, I know Phil had edited the template to not show h5 and h6 headers, which is ideal in most cases. But it is possible to have two (or more) Kramdown ToC templates for use in different kinds of docs? I don't know, but that would seem like a sensible approach if so.

**Comment by Bloke** [comment]
The subheading thing is still an issue if we use the include with its preamble. I was just wondering if we cared about the lack of subheading in the final tag doc. So all we see is a link to "Attributes", with no link to 'Common presentational attributes' and no link to 'Global attributes'.

If we decide we do care, we'll have to manually construct the headings in every tag doc and then use the include to pull in just the attributes list.

**Comment by wion** [comment]
> I was just wondering if we cared about the lack of subheading in the final tag doc's ToC. So all we see is a link to "Attributes", with no link to 'Common presentational attributes' and no link to 'Global attributes'.

Speaking for myself, a single link to 'Attributes' is fine. Who doesn't know at this point that by clicking that you're going to see some information about attributes, plural. It's a small, independent step from there to scroll/browse to the types. 

A moot issue in my opinion.

**Comment by Bloke** [comment]
Suits me! I consider this topic closed as all we need to do is roll this out to all tag pages.
