### ISSUE TITLE
Footnotes styling

### ISSUE THREAD

**Issue by wion** [textpattern/textpattern.github.io#16]
I know it's a little early yet, but just putting these thoughts here as they come to light.

One thing I'm using in docs, which is quite useful to separate primary content from secondary help, is footnotes (e.g., see them used [on this page](https://github.com/textpattern/textpattern-documentation/blob/master/administration/index.textile)):

```
...end of paragraph.[1]

fn1. Sidenote here...
```

But they look a little funny right now because their not distinctive from the main copy. I'd propose making the footnote text a little smaller and perhaps a slightly different color in the Jekyll version to clearly set them apart.

**Comment by philwareham** [comment]
The Jekyll site will use the new Textpattern.com design (vaguely similar to forum design but not restrained by the font size we use there) - all elements will be ours to style however we like.

**Comment by wion** [comment]
@philwareham 

Just to follow up on this for when your ready. The only thing that bothers me about footnotes in the Jek site at the moment is the color contrast isn't strong, and the font size is practically unreadable in Firefox (okay in Safari, others I haven't checked). 

Maybe you just need to play around with some options when the time comes, but obviously we want that text to be a little different than the main body text; smaller in relation but bigger than it is now (bumping the main body font size up too in relation). And maybe instead of a lighter color (or poor contrast), you try using italic, or serif. Whatever.

Assigning to you. ;)

**Comment by philwareham** [comment]
Footnote style has now been done.
