### ISSUE TITLE
page: /tags/file_download

### ISSUE THREAD

**Issue by joopvos** [textpattern/textpattern.github.io#161]
### Absolute URL of front-end page

{https://docs.textpattern.com/tags/file_download}

### The question/problem

{Link on "file-tags" (2x) gives 404 ... :o}

**Comment by Bloke** [comment]
[Fixed](https://docs.textpattern.com/tags/file_download). Thank you. There's going to be a lot of this sort of thing about right now as we move a few things around in the docs.
