### ISSUE TITLE
page: tag categories

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern.github.io#164]
### Absolute URL of front-end page

All tag category lists are now broken - for example https://docs.textpattern.com/tags/article-tags gives a 404

### The question/problem

Somebody has moved or deleted the tag category listing pages. Please reinstate/revert from history.

**Comment by Bloke** [comment]
I moved them. Where are they broken? The ones at the top of the tags page are fine but I guess there may be references from within tag docs that point back to them.

If there aren't too many, I'll update the references, but if there are too many to do now, I'll temporarily copy the files back to the main /tags dir until we fix them all.

**Comment by philwareham** [comment]
> Where are they broken?

In the foot of a plugin article. I think you'd be able to find/replace fairly easily to point to the amended URLs. Thanks Stef.

**Comment by Bloke** [comment]
I'm being dim. I did a global search in the docs repo for `/tags/[a-z]*-tags` and came up empty. What am I missing?

**Comment by Bloke** [comment]
Ah, thanks. Sorry for the hassle. Thought I'd caught them all.

**Comment by philwareham** [comment]
Breadcrumbs are still broken but I'll try to work out a fix for that in the collection page template if I can.

In retrospect, I kind of wish we hadn't moved the tag page directory structure about. The only marginal benefit I can see is for us, the editors - directory structure is irrelevant to end users. Oh well.

I assume the tag basics directory is being deprecated in favour of the 'learning' article?

**Comment by Bloke** [comment]
Yes, all those tag basics articles are going to die.

If it causes too much pain, let's put the *-tags articles back in the main folder.

**Comment by philwareham** [comment]
It's fixed up now so let's leave as-is. Any oirganic links will eventually repoint - I've resubmitted a new sitemap to major search engines to hopefully silence my search console 'issue detected' emails.

**Comment by wion** [comment]
All we're talking about is a few links. It's not a big deal. And if the few changes make it easier for volunteer editors to maintain docs, it's not 'marginal', it's significant.
