### ISSUE TITLE
Request for prefix: all

### ISSUE THREAD

**Issue by gizulor** [textpattern/textpattern.github.io#169]
## What prefix do you want to register?

all

## Provide link to your Textpattern forum account profile.

https://forum.textpattern.com/profile.php?id=1885
## Can we expect a theme, a plugin, or eventually both?

- [ ] Themes only

## Do you have a theme or plugin ready to share, or close to it?

- [ ] Yes

**Comment by philwareham** [comment]
OK, prefix added. Thanks for collaborating!
