### ISSUE TITLE
Moved install -> No pagination on front page(s)

### ISSUE THREAD

**Issue by jauntyd** [textpattern/textpattern.github.io#170]
Hopefully there is just something I overlooked, but here is my issue:

I moved my install and everything shows up great. All my content is there and I can connect to the new database. However, when I click the "Older" link on the front page (at the bottom), the url changes as if it were working correctly, but the content displayed is the first page content. The content doesn't change when I click "Older". This feature works great on the original install. 

I have verified that all modules are installed via php -m:
[PHP Modules]
Core
date
filter
hash
json
libxml
mysqli
mysqlnd
pcre
Reflection
session
SimpleXML
SPL
standard
xml

I am also able to access the content that should be displayed on page 2, 3, 4, etc. I can also see the content in my admin panel. I am not sure where to begin troubleshooting this, so any guidance or (hopefully) a repair would be nice.

I thoroughly enjoy using Textpattern!

**Comment by jauntyd** [comment]
Something I just noticed that I think is worth adding....
The "prev" link does not show after clicking "Older", even though the URL changes to the next page.

**Comment by petecooper** [comment]
Hey @jauntyd - I'm a Textpattern-on-Nginx guy, try this instead:

```
try_files $uri $uri/ /index.php$is_args$args;
```

It's a slightly tighter match on the PHP stuff, and also permits directories to be tried before bailing out to the `index.php`.

That said, it looks like you're all good, I'll close the issue.
