### ISSUE TITLE
Request for prefix: zoo

### ISSUE THREAD

**Issue by gud0** [textpattern/textpattern.github.io#171]
## What prefix do you want to register?

zoo

## Provide link to your Textpattern forum account profile.

add URL here

https://forum.textpattern.com/profile.php?id=707

## Can we expect a theme, a plugin, or eventually both?

- [y] Themes only
- [ ] Plugins only
- [ ] Perhaps both

## Do you have a theme or plugin ready to share, or close to it?

- [n] No
- [ ] Yes

(Checking 'No' does not mean you can't register a prefix, but it does mean someone can challenge your claim to the prefix if they produce a product before you do.)

**Comment by petecooper** [comment]
Done!

**Comment by gud0** [comment]
Hi Pete, sorry about this...

Please can you change my prefix from ZOO to GUD. I haven't used ZOO at all. It was near to ZERO my forum name, but otherwise irrelevant, but someone will like that name. GUD relates to my website on which my themes will be hosted (one coming up later today, another in a few days). Hoping to get my head around github too and put the code on there, fwiw.

Hoping that's not much hassle

All the best // Pete (zero)

-- 
Securely sent with Tutanota. Get your own encrypted, ad-free mailbox: 
https://tutanota.com


30 Jun 2020, 16:16 by notifications@github.com:

**Comment by petecooper** [comment]
Done!

**Comment by gud0** [comment]
Brilliant! Thanks Pete

-- 
 Securely sent with Tutanota. Get your own encrypted, ad-free mailbox: 
 https://tutanota.com


27 Jul 2020, 08:34 by notifications@github.com:
