### ISSUE TITLE
proposed: extended `config.php` options

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern.github.io#175]
Proposed title and location of new page...
/administration/extended-configuration

## Situation/Scenario for proposal

Catch-all doc for post-install config settings that are not for beginners (read: those reading the install docs).

## Value

Holding pen for all the undocumented `config.php` options not covered by the user-created file at install time.

## Related issues

https://github.com/textpattern/textpattern/issues/1444
https://github.com/textpattern/textpattern/issues/1256

**Comment by Bloke** [comment]
We have [the post-installation docs](https://docs.textpattern.com/installation/post-install-and-upgrade-routines) currently but I don't know how much (if any) of that made it to the [new docs area](https://docs.textpattern.com/index2). Might be worth harvesting the old doc and linking it into the new index page.

**Comment by petecooper** [comment]
Thanks @Bloke - appreciated. Leave it with me, I'll need a bit more patience and time to pick through it, but we'll find a way.
