### ISSUE TITLE
Request for prefix: add prefix here

### ISSUE THREAD

**Issue by temene** [textpattern/textpattern.github.io#177]
## What prefix do you want to register?

tem

## Provide link to your Textpattern forum account profile.

https://forum.textpattern.com/profile.php?id=205782

(The forum profile link is required. No profile link, no prefix registration.)

## Can we expect a theme, a plugin, or eventually both?

- [ x ] Themes only
- [ ] Plugins only
- [ ] Perhaps both

## Do you have a theme or plugin ready to share, or close to it?

- [ ] No
- [ x ] Yes (it is done - but it is very simple, as discussed on the forum)

(Checking 'No' does not mean you can't register a prefix, but it does mean someone can challenge your claim to the prefix if they produce a product before you do.)

**Comment by philwareham** [comment]
Prefix added, thanks for contributing!

**Comment by temene** [comment]
Gosh, it is such a small contribution though. I am not sure that I understood how themes are hosted, but it can be found here: [https://github.com/temene/tem](url). Albest!
