### ISSUE TITLE
Default article "next steps" landing page / portal

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern.github.io#182]
https://github.com/textpattern/textpattern/issues/1574

We're going to simplify the default article and have a landing page with appropriate content, rather than link stuffing in the article. This is a placeholder issue to track progress.

**Comment by philwareham** [comment]
Cool. Once I know what the welcome article will contain, we can decide what (if any) of the older welcome article needs to come across - or if a new next steps article needs to entirely written from scratch. Will keep an eye out.

**Comment by petecooper** [comment]
Not needed, revised default point to docs index. Closing.
