### ISSUE TITLE
Change to 'Contents' on ToCs

### ISSUE THREAD

**Issue by wion** [textpattern/textpattern.github.io#185]
A proposal to change all text strings above the contents lists to just '**Contents**' (no colon), instead of 'Table of contents' or 'On this page:', because it's clean, clear, and accurate to the element, not to mention being the de facto standard in most publishing. The Oxford Style Manual suggests it, for example, and I think we've accepted that reference as guide along with the OED, right?

There's currently a combination of all three across docs, and I'm sure I'm guilty of this in the past, and probably the docs guide and page template needs revised (I'll check).

But I do not propose that these all be changed immediately, and especially if manually. Is there an easy way to do a find/replace at the tree level?

[APPROVED] / [DECLINED]

**Comment by philwareham** [comment]
APPROVED - you can probably just do a search/replace to quickly change all of these.

**Comment by Bloke** [comment]
Yeah, makes sense.

**Comment by philwareham** [comment]
I'll do this for you.

**Comment by philwareham** [comment]
Done.
