### ISSUE TITLE
Request for prefix: day

### ISSUE THREAD

**Issue by revdazza** [textpattern/textpattern.github.io#187]
## What prefix do you want to register?

daz

## Provide link to your Textpattern forum account profile.

https://forum.textpattern.com/profile.php?id=1961

(The forum profile link is required. No profile link, no prefix registration.)

## Can we expect a theme, a plugin, or eventually both?

- [ ] Themes only
- [ ] Plugins only
- [ x] Perhaps both

## Do you have a theme or plugin ready to share, or close to it?

- [ ] No
- [ x] Yes

(Checking 'No' does not mean you can't register a prefix, but it does mean someone can challenge your claim to the prefix if they produce a product before you do.)

**Comment by petecooper** [comment]
All done @revdazza – thanks for your interest and patience.
