### ISSUE TITLE
FAQ: Diagnostics

### ISSUE THREAD

**Issue by wion** [textpattern/textpattern.github.io#20]
The [FAQ: Diagnostics category](http://textpattern.com/faq/?c=diagnostics) and two associated FAQs at .com can be removed and redirected to [new Diagnostics doc](http://docs.textpattern.io/administration/admin/diagnostics-panel).

**Comment by wion** [comment]
Assign this to whoever is working on .com content (and has access to .com admin-side).

**Comment by philwareham** [comment]
OK, redirect done temporarily. Will revisit once all the FAQs have been formatted properly here and FAQ categories removed from .com

**Comment by wion** [comment]
Just so we're on the same page, it's not my intention to simply port the FAQs to Jekyll. Most of those FAQs are highly redundant with doc content, and simply need to be properly edited into place. So by the end of it all, there shouldn't be any FAQs, or at least very few. At that point it will be enough to simply point people with relevant questions to the proper doc page. Sorry if I misunderstood what you're saying.

**Comment by philwareham** [comment]
Yep, I agree. FAQs shouldn't be needed once their content is reviewed and placed into proper documentation pages.

**Comment by wion** [comment]
The redirect will need corrected due to the recent doc tree changes. The path should now be...
http://docs.textpattern.io/administration/diagnostics-panel

**Comment by philwareham** [comment]
Done.
