### ISSUE TITLE
Request for prefix: cad

### ISSUE THREAD

**Issue by Chiropteron** [textpattern/textpattern.github.io#205]
## What prefix do you want to register?

cad

## Provide link to your Textpattern forum account profile.

https://forum.textpattern.com/profile.php?id=206348

(The forum profile link is required. No profile link, no prefix registration.)

## Can we expect a theme, a plugin, or eventually both?

- [ ] Themes only
- [ ] Plugins only
- [x] Perhaps both

## Do you have a theme or plugin ready to share, or close to it?

- [ ] No
- [x] Yes

(Checking 'No' does not mean you can't register a prefix, but it does mean someone can challenge your claim to the prefix if they produce a product before you do.)

**Comment by petecooper** [comment]
Done- thanks @Chiropteron
