### ISSUE TITLE
Request for prefix: rsx

### ISSUE THREAD

**Issue by funkaoshi** [textpattern/textpattern.github.io#207]
## What prefix do you want to register?

I already am the owner of the `rsx` prefix, but it's not linked to any account. (Likely because it existed before that was a thing.)

## Provide link to your Textpattern forum account profile.

[Ramanan](https://forum.textpattern.com/profile.php?id=392)

## Can we expect a theme, a plugin, or eventually both?

- [ ] Themes only
- [X] Plugins only
- [ ] Perhaps both

## Do you have a theme or plugin ready to share, or close to it?

- [ ] No
- [X] Yes

I already have several plugins registered. I was planning on reviewing them and seeing which ones need updating.

**Comment by petecooper** [comment]
Done - thanks @funkaoshi!
