### ISSUE TITLE
Request for prefix: ais

### ISSUE THREAD

**Issue by Ashley-Butcher** [textpattern/textpattern.github.io#208]
## What prefix do you want to register?

**`ais`** (= Alien Internet Services)

## Provide link to your Textpattern forum account profile.

https://forum.textpattern.com/profile.php?id=206460

## Can we expect a theme, a plugin, or eventually both?

- [ ] Themes only
- [X] Plugins only
- [ ] Perhaps both

## Do you have a theme or plugin ready to share, or close to it?

- [X] No[^1]
- [ ] Yes

[^1]: Ultimately this all depends on your definition of "close"... I'm working on a plugin for a client that is nearly ready to go into UAT, but it has a wider community benefit as it brings some functionality to Textpattern that's missing. I think that with a bit of spit and polish, it should be ready to be released so it can run free and frolic with the other plugins in the wild. It's likely to be several months before the little scoundrel is ready for me to open the cage, therefore I assumed that doesn't quite cut it as "close" and hence answered "no" here. Oh my, here I am rambling away while there's spitting and polishing to do. My apologies. Thank you in advance! Now, where did I put my elbow grease...

**Comment by petecooper** [comment]
Thanks @Ashley-Butcher – done
