### ISSUE TITLE
Table styling

### ISSUE THREAD

**Issue by wion** [textpattern/textpattern.github.io#21]
Phil, I know you've not finished styling, but I just want to put in my vote for zebra-striping rows instead of using row borders only on all-white background like they appear in the forum. If you need a table to work with, here's a good one... 
http://docs.textpattern.io/administration/admin/user-role-types-and-privileges

**Comment by philwareham** [comment]
Tables will need to be wrapped in `<div>` tags and have a `class` of them like so:

    <div class="tabular-data">
        <table class="">
            ....content...
        </table>
    </div>

There are some [design patterns here](http://textpattern.com/mockups/design-patterns.html#section-tables), but it's old and the styling is wrong, but it gives some guidelines.

**Comment by philwareham** [comment]
I will look at zebra striping though, makes sense here,

**Comment by wion** [comment]
Ok, so I guess I need to _not_ use Textile tables then.

**Comment by Bloke** [comment]
You can do that in Textile(ish) by manually adding the div around it and using the:

    table(table-bordered).
    |_. Heading 1 |_. Heading 2 |
    | ... | ... |

syntax to add a table class. See [docs](http://txstyle.org/doc/15/tables) for examples.

**Comment by philwareham** [comment]
You would need to use...

    .notextile <div class="tabular-data">

Then leave a blank line, then your normal Textile table as Stef says. Then...

   .notextile </div>

Sorry I know it's a little bit clunky but that's the only way to get the tables to work nicely on thin screens. Or, we could use jQuery to insert the `<div>` tags, but I'd rather not rely on JavaScript for this.

**Comment by Bloke** [comment]
Does it not recognise the leading space(s) trick to bypass Textile, or is the `notextile.` necessary?

**Comment by philwareham** [comment]
I guess so, but `.notextile` would be more intuitive/visible when someone comes to edit these docs a couple of years down the line.

**Comment by Bloke** [comment]
True dat. As you were...

**Comment by wion** [comment]
That's just a formatting rule that goes into the docs-specific part of the style guide, so it can be defined whichever way is preferred. We just might want to be consistent.

**Comment by wion** [comment]
If I do this, the Textile table renders fine but it leaves `.notextile` visible in the page:

```
.notextile <div class="tabular-data">
	
|_. Data item |_. What it tells you |
| Textpattern version: | whatever version you have installed |
| Last update: | |

.notextile </div>
```

If I do this (replace `.notextile` with a space) the Textile table is not rendered:

```
 <div class="tabular-data">
	
|_. Data item |_. What it tells you |
| Textpattern version: | whatever version you have installed |
| Last update: | |

 </div>
```

Am I doing something wrong?

**Comment by Bloke** [comment]
Yes, it's `notextile.` (period after the word).

**Comment by wion** [comment]
Ah, just like convention. ;) I was confused by Phil's earlier example (and the combined use with a div and space). All good now.

**Comment by philwareham** [comment]
Sorry, I was getting my CSS and Textile languages mixed up!

**Comment by wion** [comment]
@philwareham , if you find the time to make one presentational fiddle with the docs, please let it be this one. Some cell padding and zebra striping would go a long way.

**Comment by philwareham** [comment]
OK no problem, I'll do it later today.

**Comment by philwareham** [comment]
OK done. I've made all tables have borders and zebra striping so you won't need to use `table--bordered` class now.

**Comment by wion** [comment]
Looks great. Thanks.
