### ISSUE TITLE
CSS file only partially loaded with an error

### ISSUE THREAD

**Issue by rwetzlmayr** [textpattern/textpattern.github.io#210]
If you visit https://docs.textpattern.com/ and its subpages, the result is a rather unstyled document.

![docs textpattern com_(iPhone SE)_2](https://github.com/textpattern/textpattern.github.io/assets/357054/4443f185-a1b0-4ac4-a269-22d797046914)

This may be due to the fact that `https://textpattern.com/assets/css/screen.css` is not accessible. Firefox reports `NS_ERROR_NET_PARTIAL_TRANSFER` for this request, Chrome reports merely `ERR_HTTP2_PROTOCOL`.

**Comment by philwareham** [comment]
<img width="576" alt="Screenshot 2023-11-24 at 11 16 23" src="https://github.com/textpattern/textpattern.github.io/assets/413665/799f6760-8164-4e29-b3dd-8537433e73fa">

The stylesheet should be loaded from the Textpattern.com site (they share a CSS file), seems like some HTTP2 error according to Chrome error console - @petecooper any ideas (or any changes done to the server recently which might have caused this)?

**Comment by rwetzlmayr** [comment]
> The stylesheet should be loaded from the Textpattern.com site 

In possibly unrelated news, Chrome also reports `Access to fetch at 'https://textpattern.com/assets/img/branding/textpattern/textpattern-og.png' from origin 'https://docs.textpattern.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

**Comment by rwetzlmayr** [comment]
This issue currently also occurs at the [forum site](https://forum.textpattern.com/). 

![txp-forum](https://github.com/textpattern/textpattern.github.io/assets/357054/8785ca26-d16c-400b-9f51-48cb572a99d9)

**Comment by petecooper** [comment]
Tagging for completeness https://github.com/textpattern/textpattern-forum/issues/673

**Comment by petecooper** [comment]
No changes to HTTP implementation, I'll have some time later today / tonight to take a closer look.

Thanks @rwetzlmayr for the report!

**Comment by philwareham** [comment]
Have you deployed anything to the server recently. I noticed this commit a few weeks back which is to do with HTTP2?

https://github.com/textpattern/server-config/commit/2daf3830d3634ace21b8e00051df8c723bdce1fc

Just a guess though, I have limited server knowledge.

**Comment by petecooper** [comment]
Nginx recompiled with a different TLS library ~48 hours ago, I suspect that's it - I can roll back later today.

**Comment by gas-kirito** [comment]
Hi, I noticed that on the page <https://docs.textpattern.com/build/themes-creating-using-and-sharing> all the content under a certain line is garbled. I copy-pasted an extract down here. In the console, Firefox complains about an encoding issue. Could this be somehow related to the `screen.css` issue?

```
[...]
For clarity, here are the counts and types of theme asset pairings to sections reflected in Table 1:

    three one-to-one page pairings to sections: default (1), archive (1), error_default (1)
    two one-to-many page pairings to sections: generic (2), hothouse (6)
    oneeeeeeeeeeeeestyle pairing to a section: 404 (1)
    two one-to-many style pairinggggggggggggggggggggggggg4), veggies (6).

The map allows setting up a Textpattern websiteestructure and theme development environment with purpose. With the map at hand, we can use what has already been learned in earlierto a sectitd>artHis docunt w. And ife caproce in eaa particular order, a lotd>arjumpg uparounddddddde back endan usbe eliminated.
h3 id="create-the-needed-a sectit">Createddde needed a sectit r-data" tabindex="0" aria-labeo ens in tf="#add-or-edit-livetit r-daindex="0" a> youreadprjumpgyour blueprints tabl r-at do not sectitd>exist. Only ch3d> caproce r-at are miss fromgyour blueprints,ith pdo not edit or deletwithy caproce r-at aectitd>exist. Exist caproce apply

Theurpos. Eithern ear caproce r-at exist ae r-ey are, or ch3d> newggggs sectit"p>IIIIIIIIIIIIIIwen earr-daggggexist

The/li> ‘

Th’ith p‘��������’i(restr1ith p222222222222). No d sectit"p>For eachgggg, clickrr-daNewr caproc button. Add r-datamwith puitleeeeeeeer caproc,is dvarr-da

Theurpos selected (four-point-eight),ith pselectp

hlank oppppppforpppppfuw-wAnd ifowppppppppfuorAnd ifoispos selec> d sectitTheursd> nvetit</ <p>hlaassets d sectitSis dvarr> nvetitIIII: d sectitTheursd> ly ests tisha tabindex d sectitItlop�easys (6). dvarr> nvetitTh�ppears). We could his deasilyIwenddnerio Eithc (2)orAnd ifonk oppsted.
[...]
```

**Comment by petecooper** [comment]
Hmm. Thanks for the report @gas-kirito - I will investigate ASAP.

**Comment by petecooper** [comment]
@rwetzlmayr @gas-kirito I think this is now resolved. Please retry and report back. Thank you.

**Comment by gas-kirito** [comment]
It all seems to be working fine to me. Thanks!

**Comment by petecooper** [comment]
Closing pending feedback from @rwetzlmayr

**Comment by rwetzlmayr** [comment]
Better late than never, my feedback is: Works as expected - perfect!
@petecooper Thank you very much!
