### ISSUE TITLE
Tag attributes cross-reference page: All H3s have a constant prefix number 0.1.

### ISSUE THREAD

**Issue by rwetzlmayr** [textpattern/textpattern.github.io#214]
#### URLs

- Back: https://github.com/textpattern/textpattern.github.io/tree/master/tags/tag-attributes-cross-reference.md
- Front: https://docs.textpattern.com/tags/tag-attributes-cross-reference

#### Explanation of immediate task

The attribute names contained in the ```H3```s are prefixed with a constant useless ordinal number '0.1'. Their ordinal number does not increase from attribute to attribute, but remains '0.1' throughout the document.

The header counters are controlled by this CSS rule: 

```
.article--with-toc h3:before {
    content: counter(heading-h2-counter) "." counter(heading-h3-counter) " " " ";
    counter-increment: heading-h3-counter;
    opacity: .66;
}
````

#### Current to-dos

- [ ] Think about whether the numbering of these headings serves any positive purpose.
- [ ] Change the CSS rule to get the numbers right. I don't speak modern CSS, so I have no solid idea what to do.

**Comment by petecooper** [comment]
>Think about whether the numbering of these headings serves any positive purpose.

My 2c: it serves no positive purpose.

**Comment by philwareham** [comment]
The template this page used expects a table of contents. I have now crested a template option that does not expect that, and assigned it to the offending article.

The next time someone builds the Jekyll site, it should be fixed. Thanks for the report.

**Comment by petecooper** [comment]
I'll force a rebuild now.
