### ISSUE TITLE
Add all possible (encoded) pre-flight check messages to Diagnostics doc

### ISSUE THREAD

**Issue by wion** [textpattern/textpattern.github.io#22]
Stef,

Is there any way to get a complete list of all yellow and red pre-flight messages that could appear? Just the messages themselves would be helpful. They must be encoded somewhere, right? I need them to make a complete and accurate cross-reference with the messages in the doc page, where some are probably missing and wrong (in the case of the red ones).

http://docs.textpattern.io/administration/admin/diagnostics-panel

**Comment by wion** [comment]
Phil,

Note that I've added inline styles for the green, blue, yellow, and red messages. It would be nice to add a class selector for those when you get to the CSS. 

The only colors I couldn't verify accurately are the red messages, because I didn't try to generate any red errors to pull up the source CSS.

**Comment by wion** [comment]
Stef,

Another question... The __Functions not used by Textpattern__ section in the Diagnostics doc was pulled from the same FAQ on the topic. But I'm unclear where the following warning appears, whether as a pre-fight check or actually in the info field:

    The following PHP functions (which may be necessary to run Textpattern) are disabled on your server…

If that's a pre-flight check, can you tell me what color?

**Comment by philwareham** [comment]
You can use...

    class="success"
    class="warning"
    class="error"

...either inline or on block element.

**Comment by Bloke** [comment]
Here's the list scraped from `txp_diag.php`, plus an indication of whether they're information (blue) or warning (orange? red? can't remember). Presumably the ones that don't have a designation are "information" as I think that's the default.

    textpattern_version_update      information
    php_version_required
    path_to_site_missing            warning
    dns_lookup_fails                warning
    path_to_site_inacc
    site_trailing_slash             warning
    index_inaccessible
    dir_not_writable
    cleanurl_only_apache            information
    htaccess_missing
    mod_rewrite_missing
    file_uploads_disabled           information
    setup_still_exists              warning
    no_temp_dir                     warning
    warn_mail_unavailable           warning
    warn_register_globals_or_update warning
    old_placeholder_exists
    modified_files                  warning
    dev_version_live                warning
    missing_files
    some_php_functions_disabled     warning
    site_url_mismatch               warning
    clean_url_data_failed           warning
    clean_url_test_failed           warning
    mysql_table_errors
    tmp_plugin_paths_match

If you look up those strings in your txp_lang table you'll get the phrases.

**Comment by wion** [comment]
Stef, 

If you will indulge me a minute, this is what I would expect to see in terms of message encoding logic from a UX standpoint:

 - "success" = green : Default, because it's the desired state. (Note, "All checks pass!" is not listed.)
 - "information" = blue : Should only be items that relay a message that does not require taking action as far as system functionality is concerned. I.e, blue should not be items that indicate a functional or potential functional problem (yellow) or critical-fix-ASAP situation (red).
 - "warning" = yellow : Should only be items that indicate functional, or potential functional problems.
 - "error"  = red : Should only indicate absolute system show-stoppers; critical-fix-ASAP situations.

As far as I can tell with the items listed above that are *marked*, the logic is okay, with exception of maybe the last two "information" items... They look like they might be better encoded as "warning".

As for all the unmarked, I'd guess to see them marked as follows (Are they unmarked because nobody bothered marking them, or because it's necessary to leave them unmarked?)...

Unmarked lines that look like "error" (red) messages:

 - php_version_required
 - index_inaccessible
 - dir_not_writable
 - htaccess_missing
 - mod_rewrite_missing
 - missing_files
 - mysql_table_errors

Unmarked that look like yellow:

 - path_to_site_inacc
 - old_placeholder_exists
 - tmp_plugin_paths_match

And these marked as "information" should possibly be yellow?:

 - file_uploads_disabled
 - cleanurl_only_apache (not exactly sure what this one means)

**Comment by Bloke** [comment]
I lied, sorry. The type defaults to 'error' (show-stopper) if omitted. *All checks passed* is indeed rendered with `class="success"`. So that means unmarked ones are all critical problems as you noted.

With regards the anomalies you highlighted:

* `path_to_site_inacc` is pretty darn fundamental as it'll break virtually everything if it's wrong. It's so important I think Txp checks it every (admin-side?) page view. Might be wrong, it's been a while since I looked.
* `old_placeholder_exists` can break your site if you have a folder named the same as one of your Sections, hence its potential site-breaking nature probably lends credence to its 'error' status.
* `tmp_plugin_paths_match` I'm not sure of the ramifications here if your plugin cache is the same as your tmp files. In theory neither should be web accessible but if you set them to the same location, well, maybe the fear is that a temp file overwrites a plugin, which would be bad. Potential for that to happen? Dunno. Not high I would think, so maybe we could downgrade this one unless someone can come up with a scenario on why it's critical.
* `file_uploads_disabled` isn't this just information? If your site doesn't use Files, it's not important to you.
* `cleanurl_only_apache` presumably means that clean URLs are only (officially) supported on Apache and not IIS or any other system you may have installed. So it's kind of informational, because if you've violated the minimum system requirements in this manner, the implication is you know what you're doing so don't need to be nagged about it.

Make sense or am I way off?

**Comment by wion** [comment]
Great. Thanks. I'll wade through all of this so far and see where things are at after that.

**Comment by wion** [comment]
Stef, 

Does the blue, "file_uploads_disabled" message work in relation to the Basic > Admin preference, "File directory path"? I.e., no path means you've disabled file uploads?

If not that, then where is the "disable" location that corresponds with this blue message?

**Comment by wion** [comment]
Nope, that's not it. I just thought to test, it throws a yellow warning instead. So, what needs to be disabled, exactly,  and where, to get the blue message?

Sorry to be annoying, but these will be very useful docs.

**Comment by Bloke** [comment]
I think 'file uploads are disabled' shows up when the permissions of the underlying nominated path are insufficient to permit writing. So try cranking down the permissions to read only and see if that message appears.

**Comment by wion** [comment]
Thanks, Stef. I haven't tested that yet, but I've added that on the message so it can be verified at some point. ;)

**Comment by wion** [comment]
Another question... I see these two data items at top of diagnostics info display, which in my site give the same path:

  - Document root: /users/home/{me}/web/public
  - $path_to_site:  /users/home/{me}/web/public

I would expect the second one to appear as "Path to site:" if it was supposed to show at all (human friendly label). Is there a difference? Redundanc? Problem?

**Comment by wion** [comment]
And this one, which comes directly under the two above...

  - Textpattern path:

Is a little confusing as a label because it makes it sound like the same path (textpattern installation path). I'd suggest changing it to "Configuration directory path:", especially as someone might choose to change the name of their config directory, with necessary or not.

**Comment by wion** [comment]
Be warned I will probably comment on others too if I see possible improvement, but I leave on vacation for a week beginning Saturday, so you will likely be spared for at least that long.

**Comment by wion** [comment]
I've just cross-referenced all the blue, yellow, and red pre-flight messages as they've been identified in this thread so far. The blue are covered, but I don't find the following yellow and red names in the `txp_lang` table:

**Warning (yellow):**

  - dev_version_live
  - no_temp_dir
  - path_to_site_missing
  - warn_mail_unavailable

**Error (red):**

  - mysql_table_errors
  - php_version_required

This one is in the table, but there's no phrase given for it, and I'm not sure if it's a warning or an error:

  - path_not_doc_root

Finally, I notice some phrases have period endings (like a sentence), and some don't. For consistency, I would recommend one or the other for them all. It doesn't matter which way, just be consistent.

**Comment by Bloke** [comment]
Have you updated your languages to the latest set, from Admin->Preferences->Languages? The following all exist in my `txp_lang` database:

* `no_temp_dir`
* `path_to_site_missing`
* `mysql_table_errors`
* `php_version_required`

You're right that `path_not_doc_root` is missing a translation. It's not in the textpack at all. Presumably it's an old string that's been phased out, as it's not used anywhere. Ignore it.

Two anomalies:

* `warn_mail_unavailable` is in the textpack but for some reason is not pulled down into the local database when langs are updated. Needs investigation. Any ideas @philwareham, @petecooper? Has it slipped through the net on RPC?
* `setup_still_exists`: mea culpa. The actual string is just `still_exists`. Sorry.

And yes, we should standardise on trailing periods, but there are a number of phrases that are used as part of other strings or in multiple places so they sometimes don't have them. Pete's on the ball at catching these and has done many of them already, so it may be that your lang table is just out of sync with the master copy.

**Comment by petecooper** [comment]
I suspect `warn_mail_unavailable` is an RPC oversight. Will investigate. Give me 5 mins to confirm.

**Comment by petecooper** [comment]
Hmm - `warn_mail_unavailable` is present in RPC (line 1059) and the Textpack (line 1017).

**Comment by wion** [comment]
Turns out I was looking at a lang table from the previous install version. *sigh*
I'll update and revisit.

**Comment by wion** [comment]
So that outdated site was updated and the Language preferences too afterward, but I still don't see those pre-flight names in the `txp_lang` table.  I'm not worried about that if my site still works, but if someone could be so kind as to just give me the associated data phrases, I'll update the doc.

**Comment by wion** [comment]
This conversation is pretty much in the associated forum thread now...
http://forum.textpattern.com/viewtopic.php?id=46350
