### ISSUE TITLE
"Partials"

### ISSUE THREAD

**Issue by wion** [textpattern/textpattern.github.io#23]
There's a been a lot of talk about changing the name of Txp "forms" to something else, and "partials" seems to be what Robert likes, based on his rare forum input. Can someone confirm if this a a green light in the next release? Because if so, then now is the time to write the new docs with that change in mind, instead of later when there's a zillion needless instances of it to change.

**Comment by philwareham** [comment]
@rwetzlmayr and @Bloke - what's your thoughts on this? I'd love to change the name of 'forms' but think it may be unfeasible due to long history? Would like to hear your opinions.

**Comment by wion** [comment]
You didn't ask me, but regarding legacy stuff, you can't move forward without actually taking the steps. Make the changes in the official content (docs, .com, etc) and the rest will easily follow, and especially with something like this ("forms") that has never been liked. External content ROTs fast and is insignificant. Forum content is well policed and will correct itself easily.

**Comment by philwareham** [comment]
OK, as I said, I'd love to change it, but it's not up to me alone.

It's also used in a tag and an as attributes in various places.

**Comment by wion** [comment]
I realize. Just wanted to get that in there for all stakeholders to consider.

**Comment by philwareham** [comment]
Cool :+1:

**Comment by rwetzlmayr** [comment]
For me this is a "Bikeshed" issue. You can call this thing forms, partials, even [Al](https://www.youtube.com/watch?v=ULjCSK0oOlI), as long as I don't have to spend time on any changes involved.

**Comment by wion** [comment]
I don't know what's involved, but I'm guessing it's not just an easy 'find/replace all instances', kind of thing, right? 

Is this something someone in the community could "patch" to take it out of core dev hands? Should a forum request be made for that? A "We'll change "forms", but you have to provide the patch." kind of proposal?

In any case, I'll continue with "forms" until further notice.

**Comment by philwareham** [comment]
Looks like we are sticking with forms since nobody wants to take ownership of changes needed in core to facilitate a name change. Closing.
