### ISSUE TITLE
Plugins panel table > Active column

### ISSUE THREAD

**Issue by wion** [textpattern/textpattern.github.io#24]
I'd propose a couple UI content changes here...

The column header is "Active", and the data cell options are "No", and "Yes", but their respective hover titles are "enable" and "disable", which don't balance. The first is reporting on status, while the latter is indicating an action to take. 

I know it seems like a small thing, but when you start writing about stuff like this, you want these concepts to match when they are concerned with the same elements. It makes it easier to write about and for users to follow.

In this case you want the options to be verb commands (just like the hover titles are), because they are controls that must be interacted with. I.e., they're not just indicators alone (in which case things like Yes/No, On/Off, etc, would be okay, because they're just telling you something, not demanding action). The column header is where you want the indicator, and "Active" is one, but it's biased to one of the states, and not the one it would seem to suggest by default.

I propose the following changes:
- "Status" as the column header
- "Enable" and "Disable" as the cell options
- "Enable" and "Disable" as the corresponding hover titles (note the capitalization changes here)

A further nice touch would be to use the `class="success"` and `class="error"` styles to provide a green and red fill on the table cell too, just like you're using `class="warning"` in the **Modified** column. But if the cells can actually be block filled, that would be better than just links with background colors, though that's of lesser importance.

**Comment by Bloke** [comment]
I can sort of see where you're coming from, but I'm still a bit confused about the terminology.

If active plugins are designated in the status column with "Enable", anyone who's looking to see which plugins are currently switched on ("active") has to apply negative brain logic to determine what's going on:

"Alrighty, is smd_where_used currently running? Wait, so any plugins that are currently active and functional in my site are the ones that are shown with 'Disable' alongside them... wtf?"

But the current system is imperfect too:

"In order to switch off a plugin, click "Yes".

Riiiight!

**Comment by wion** [comment]
Hmm... I'm not following the logic. So in my view, I'd imagine this...

1. I install a plugin, look to the **Status** column (formerly called "Active"), and see a red "Disabled" link.
2. I decide to enable it, click the link, and it turns to a green "Enabled" link.

You could easily use "Activated" and "Deactivated", respectively, and it would be the same thing. No?

**Comment by Bloke** [comment]
Ah, right, if you have the past tense _enabled_ and _disabled_ visible along with the colours then yes it makes way more sense. As long as you're not red/green colour blind :-)

**Comment by Bloke** [comment]
Further: if the hover tip remains the inverse of the currently displayed option, as it is now but with proper capitalisation, isn't that still a trifle confusing?

    smd_where_used   Stef Dawson   v0.3.0   Enabled [hover: Disable]

Normally a hover state shows you more information about what the thing under the cursor _is_. In this case it's showing you what it will be if you click it, but is that clear enough with just a single word?

Is there some better UI paradigm we can adopt? Perhaps rejigging the panel a bit to fit in some inline help somewhere instead? Especially since hovers leave mobile tappers out in the cold.

**Comment by wion** [comment]
Um, yes, you're right about the inverse on the hover, and not using past participles (e.g., Enabled) on those verbs. Doh. Oversight on my part their because I don't normally think of `title=""` attributes as tooltips, but it works in this case, and thus would need the inverse, of course.

And I see I did confuse the conversation by talking about verbs (e.g., "enable"), and then switching up with their past participle midway (e.g., "enabled"). My bad.

As for color, you're right, but there would still be the text, "Disabled" / "Enabled", which would appear as dark gray on lighter shades of gray backgrounds, I guess, and be a bigger clicking target if the cell is not made block-filled, so still more win than loss, I think.

In any case, If I'm not selling you on it, don't worry about it. It's not my intention to railroad things through. But as I work on docs, it does bring me closer to little details like this and I think it's worth bringing them up for consideration at least. I can say I did my part. ;)

**Comment by wion** [comment]
Speaking of accessibility, I wonder if using `title=""` attributes in anchor elements as tooltips (not what they were intended for) is an accessibility violation? I don't know. But if so, you could easily put the tooltip on the `td` element itself, or on a `span`.

**Comment by Bloke** [comment]
I think your proposals are clearer and I like the colour coded idea -- perhaps the colour coding could be for the whole row if it's enabled, and just left plain if disabled? Or plain if it's enabled, but coloured amber (or something) if disabled?

The only hiccup is that (if memory serves) the function that handles display of the Yes/No toggles is hard-coded to output 'yes' and 'no' internationalised responses. Might be wrong, but if that's the case and we wanted to change that to Enabled / Disabled, we'd need to muck about with that function. It's used on the Sections panel to toggle the radio-style options too, so need to ensure it still works there.

**Comment by wion** [comment]
About the whole row color thing... Yellow is used in the **Modified** column and that would't look very good, IMO. Just at the cell would be fine, if at all, which puts the focus on the column that matters.

If it's a code hassle, then I guess it's one of Robert's "Bikeshed" situations.

I remember reading something a few years back by a prominent thinker in the UX world about shitty CMS designs, and a particular line has always stuck out in my mind from it... "It's just fucking software, fix it already!" Or something to that effect. ;)

**Comment by Bloke** [comment]
Hehehe, I'll counter that quote with one of my own:

"We can do anything, we just can't do everything."

Since you're enjoying Github so much, if you would be so kind as to raise this as an Issue on the textpattern repo and reference this topic, it'll remain on our radar. Ta!
