### ISSUE TITLE
H2 styling

### ISSUE THREAD

**Issue by wion** [textpattern/textpattern.github.io#27]
Again, I know you're not done with CSS, Phil, I'm just putting this up as I think of it for later.

One thing I notice as I work on docs is that it's a little hard to distinguish the difference between H2 and H3, aside from a slight reduction in font size. But, size aside, I'd suggest doing something unique with the H2 headers (e.g., bottom border, a symbol at side, whatever) so they better show the main sections of a given user doc.

Most in-page ToCs link to the H2 sections, and then H3s have to do with subtopics in those sections, so it's would be ideal for quick scanning to see that a given H2 section was the start of a series of content topics. As it is now, it's hard to quickly discern that. Even just a full-width bottom border on H2 headers would work great, but something.

**Comment by philwareham** [comment]
OK, I'll look into this. I've got an urgent print deadline to meet tomorrow so I won't be looking at any Textpattern stuff again until Friday at the earliest. I'll read through your list of comments and get back to you - cheers Wion!

**Comment by wion** [comment]
You don't have to juggle your time around me. I consider these "tickets" as something you devs will get to when you get to them. I'm just making note of them in this way, using "Issues", because it concerns **user docs** (Txp content in general) and it's a good/convenient way to do it (keeps track). Much better than the forum, IMO. I'm rather enjoying working in Github now. Lookout! ;)

**Comment by philwareham** [comment]
Heading sizes adjusted. Closing.
