### ISSUE TITLE
Footer addition: "Brand and user experience" column?

### ISSUE THREAD

**Issue by wion** [textpattern/textpattern.github.io#28]
I'm referring to the universal Txp footer here. Currently it has the "External links" column, but I'd propose adding at some point another column before that -- e.g., 'Brand and UX guidelines' -- with links to things like:

- Visual brand identity [todo:pw]
- Editorial style guide (todo:dw)
- HTML style guide for web platforms [done?]
- Logo files
- Theme design guide
- Plugin development guide 

Of course these things need to be fixed up first and put in a permanent spot before linking to them, but I think having a focused list in the global footer would help bring them to attention and thus get them used more.

**UPDATE, 08/11/2019**
The focus of this issue changed on [05/11/2019](#issuecomment-549719121) to adding a single link (to an existing footer list), pointing to the _brand_ directory's [_index.md_](https://docs.textpattern.com/brand/), where all collaboration references and guidelines are being listed as they emerge. The link has been added!

It was then realized the lists in the universal footer are not visible in mobile layouts, so brand resources are not accessible that way, and there is otherwise no means for the public to access those resources via mobile.

**Comment by philwareham** [comment]
Agree. Once those pieces of info become available I'll add them into the footer. I'll also revisit the links column and see if it's still current/relevant.

**Comment by wion** [comment]
I have revised the /brand [index](https://docs.textpattern.com/brand/) page. As it was written before, with all the blank 'to do' sections, was useless. But it is now perfectly functional and can be more so with time.

I would like to make a change to the original proposal of this issue. Instead of adding all those listed items to the footer as originally suggested, I now propose we add a single new item to the universal footer, labeled '**Textpattern brand and voice**', and point it at the brand index page.

I'm sure by having more eyeballs on the resources that exist, ideas and interest will come easier/faster to expand on these resources. Then as they are produced, we simply add them to the brand index accordingly.

I also propose we make separate issues for each of the different possible resources we now think are needed. My focus will soon go back to the editorial style guide (it needs some love), but I also think someone or two should starting focusing on a 'visual brand identity' gloss. Something that would help people think about design a presentation, or a white paper, or a masthead... Whatever. I still think  Potts did a good and sufficient job with the [CSF brand identity](https://csf.wion.com/brand/). I don't think Textpattern needs anything more complicated than that, but _at least_ that.

Phil, let's close this issue once (if) you add the single footer item, as proposed above, then you start a new issue solely for the visual identity gloss.

**Comment by philwareham** [comment]
@wion Hi! I've just added a link to the footer on the docs site (might need to refresh browser so see it). if you are happy with that I'll add to the forum and .com site too and we can close. Let me know. Cheers.

**Comment by wion** [comment]
Works for me. Just so there's a place for the community to find it quickly. The footer seems like the right place.

**Comment by philwareham** [comment]
I've added the link across the family of sites. Please review and close the issue if you are happy with it. Ta!

**Comment by wion** [comment]
@philwareham, the only problem, I think, is that footer lists don't appear in mobile, so when using a phone, at least, non of those useful resources are accessible. I realize you probably hid them as a design decision, but since they've become more useful, I think we should show footer lists.

**Comment by wion** [comment]
Closing. Will open a new ticket in appropriate repo if it warrants later.
