### ISSUE TITLE
Freeze editing rights on .net wiki

### ISSUE THREAD

**Issue by wion** [textpattern/textpattern.github.io#29]
If nobody has done this yet, somebody should do it at first opportunity.
https://www.mediawiki.org/wiki/Manual:Preventing_access

I think the "restrict editing to all but sysop users" would be the right choice...
https://www.mediawiki.org/wiki/Manual:Preventing_access#Restrict_editing_by_all_non-sysop_users
in case someone with admin rights needs to make an edit/note somewhere, such as on pages to tell people to go to the new corresponding location at docs.textpattern.io

cc/ @philwareham, @rwetzlmayr

**Comment by philwareham** [comment]
I think I have an admin login, so I'll check this out and get back to you.

**Comment by philwareham** [comment]
Done.
