### ISSUE TITLE
txp:comments_form attributes deprecated / moved

### ISSUE THREAD

**Issue by vanmelick** [textpattern/textpattern.github.io#30]
`<txp:comments_form/>`: Deprecated attributes 'isize', 'msgcols', 'msgrows', 'msgstyle', 'previewlabel', 'submitlabel', 'rememberlabel', and 'forgetlabel'. Apart from msgstyle (use a stylesheet instead), these attributes have moved to the individual form_comment_* tags as shown below, mostly using slightly different (but more appropriate) attribute names. Functionality and default values didn't change.

`<txp:comment_name_input />` accepts attribute 'size'.
`<txp:comment_email_input />` accepts attribute 'size'.
`<txp:comment_web_input />` accepts attribute 'size'.
`<txp:comment_message_input />` accepts attributes 'cols', 'rows'. 
`<txp:comment_remember />` accepts attributes 'rememberlabel', 'forgetlabel'.
`<txp:comment_preview />` accepts attribute 'label'.
`<txp:comment_submit />` accepts attribute 'label'.

**Comment by philwareham** [comment]
Thanks Rudd, I'll write these into the documents soon when I get some spare time.
