### ISSUE TITLE
developer prefix list: "foo"

### ISSUE THREAD

**Issue by wion** [textpattern/textpattern.github.io#32]
Maybe a question for Stef...

I've mostly gone through the entire suite of plugin developer docs, and it was clear that "abc" was the conventional arbitrary prefix for documentation purposes, so I made that official in the table...
http://docs.textpattern.io/development/registered-textpattern-developer-prefixes

But there's a prefix, "foo", in the table that someone indicated for documentation use too, but which I've not actually seen used. Nor does that seem like a good prefix idea since "foo", "bar", etc could be needed on many other code example for different reasons.

Question is, we should remove "foo" as a prefix for documentation (unless I am missing something?), but should we also make it clear that's not an option someone else can actually register?

**Comment by Bloke** [comment]
I'd be tempted to remove it. From memory I think Jukka went through and reserved a bunch (19 or so) of three-letter function prefixes that the core uses internally. So things like `get_users()` in core means that the `get` prefix for plugins is off limits. Y'know, just in case Grant Englebert Tewkesbury writes a `users` plugin.

So it's possible that we used `foo_` internally somewhere, but if we do I can't find it any more. We definitely use all the others you highlighted.

**Comment by wion** [comment]
Maybe I'll just call it off limits in red, even if not used by Txp, that way Frederico Otto Olivier doesn't take it and fuck things up down the road. (Though anyone with that name would certainly deserve the right of use.)
