### ISSUE TITLE
Plugin template

### ISSUE THREAD

**Issue by wion** [textpattern/textpattern.github.io#33]
@rwetzlmayr,

Writing you on this because you contributed to the Github location for the template files, thus seem like the point person to ask...

The "Implementation" section on the main Plugin development page...
http://docs.textpattern.io/development/
provides a link for "Plugin template", which points to this doc...
http://docs.textpattern.io/development/plugin-template

That seems unnecessarily circuitous and redundant. I don't see the point of having a current middle doc page between the plugin dev doc and the github location. 

Wouldn't it be better to point directly to the [template's Github location](https://github.com/textpattern/textpattern-plugin-template) from the aforementioned "Implementation" section, and provide all the user doc info directly in the github's README file?

**Comment by rwetzlmayr** [comment]
> Wouldn't it be better to point directly to the template's Github location from the aforementioned "Implementation" section

Yes.

> and provide all the user doc info directly in the github's README file? 

No. I think there should be one canonical place for documentation on a Textpattern-branded domain. 

The README file on a volatile code hosting service we happen to use out of convenience (which was Google Code, is Github, will be $whatever) links to the canonical place, that suffices. We would not want that this code hosting service earns links or reputation as a canonical source - they come and go and pivot at their owners decision.

**Comment by wion** [comment]
> The README file on a volatile code hosting service we happen to use out of convenience

Sure, but isn't the entire new base of user docs on Github now (Github Pages)? It's just pointing from Github to Github. What's one more link?

Anyway, no biggie. But you should probably make this change on the README page to update the link and provide a direct one to the relevant page:

> Developer documentation
> 
> Refer to the [Textpattern plugin development](http://docs.textpattern.io/development/) documentation, and notably the [Plugin template](http://docs.textpattern.io/development/plugin-template) page.

Those links are:

* http://docs.textpattern.io/development/
* http://docs.textpattern.io/development/plugin-template

**Comment by wion** [comment]
Link correction, use http://docs.textpattern.io/development/plugin-template-help

I'm changing the file name for better distinction.
