### ISSUE TITLE
Questionable plugin dev resources

### ISSUE THREAD

**Issue by wion** [textpattern/textpattern.github.io#34]
Another Q for @Bloke, I reckon...

There are two resource links at the end of the [Implementation](http://docs.textpattern.io/development/#sec10) section of the plugin development page for:
- Generate a list of tags and attributes [???]
- Command-line plugin decoder [???]

Both go to old forum threads (one clear back to zem). And after reading through them, both seem a little dubious at this point, or at least there didn't seem to be any definitive something-something to take from them due to the resulting back and forth -- not like there should be for _documentation_ (pointing to forum discussions not good documentation move, in general).

Question is (me not being a developer), can we drop these links? Or is there really any value there? If there is value, can we produce something more contemporary and official-like from them with direct links to the resource? Say:
- A script on Github to generate tags/attributes
- A reliable command-line procedure, written up proper at TXP Tips, or the .com blog?

Thoughts?

**Comment by petecooper** [comment]
Neither of these (outdated) resources are linked in the current doc, so I've removed the ToC entries and will close this now.
