### ISSUE TITLE
Core function reference

### ISSUE THREAD

**Issue by wion** [textpattern/textpattern.github.io#35]
@Bloke,

Once upon a time, someone started, in the wiki, what looked to be the "functions" equivalent of the tag reference. But it didn't get very far...
http://www.textpattern.net/wiki/index.php?title=Category:Core_Function_Reference

I have a placeholder for it in docs...
http://docs.textpattern.io/development/#sec8
http://docs.textpattern.io/development/functions/

I guess if this is going to continue, people who were working on it before must now contribute to the Github files by forking and pulling pork? That seems logical, considering Jekyll. And then a docs editor hooks it up in Jekyll once a given page is ready.

Question is, then, is this functions reference really something people will need or want to pursue? Maybe that's a question for the forum?

**Comment by wion** [comment]
Oh, also, there are links under the functions section of the plugin dev page that point to cross-reference pages...
http://docs.textpattern.io/development/#sec8

For example, http://phpcrossref.com/xref/textpattern/_functions/

Who keeps that site up to date? Is that site up to date? I seems very handy and would save a lot of work if it's reliably maintained against version code.

**Comment by Bloke** [comment]
The core function ref was a noble gesture but would have been a ball-ache to keep up to date. Now we have (a fair chunk of) documentation in the code itself -- and growing -- this inline documentation can be compiled using PHPDoc to generate HTML docs automatically. This old wiki effort can lapse.

PHPXref is Bert's baby and is kept up-to-date by him. It's bloody invaluable for newbies and also for statistics. Link to it if it makes sense to do so.

**Comment by wion** [comment]
Thanks. Will drop the core functions reference and leave external cross-ref links.
