### ISSUE TITLE
'Correct this page' insert?

### ISSUE THREAD

**Issue by wion** [textpattern/textpattern.github.io#39]
Just thinking ahead about maintaining docs under the new arrangement (limited editors, hosted on Github, etc -- all good), and it occurs to me that it would be useful to have an insert (partial) at the bottom of each page with something like this...

> "See something wrong here? Outdated info, a broken link, faulty code example, or whatever? Please [write an issue](https://github.com/textpattern/textpattern.github.io/issues) and we'll fix it." 

It should stand out from the regular page design a bit, of course but doesn't have to be a fixed element, just bottom of every page would work fine. Might even make a good buffer space between page content and universal footer, in this case.

**Comment by philwareham** [comment]
Good idea. When I'm working on templates again soon I will add this in.

**Comment by philwareham** [comment]
Done.

**Comment by wion** [comment]
Nice. Now that I see it in context, maybe the first sentence should read...

"See something wrong on this page?"

To help show the scope.

**Comment by philwareham** [comment]
Updated.
