### ISSUE TITLE
Docs  file structure

### ISSUE THREAD

**Issue by wion** [textpattern/textpattern.github.io#40]
I was running into a bunch of broken links where I knew they weren't broken before, including what should have been valid redirects from old .com FAQ links. I couldn't  figure out the problem for a while until I realized someone had changed the flat file structure of the administration pages. 

I thought I was working on all doc pages except Tags, at least initially, so we should decide now on a file structure so this doesn't come up again and break more links.

I'm flexible, but I do feel a structured flat file tree (since it is flat files and not a DB) is more usable than dumping all administration files, for example, in a single folder.

I was basically creating a main "administration" folder with a sub-structure mimicking the admin-side panels:

* /
 * administration
   * admin
     * index (users, the default panel)
      * diagnostics-panel
      * prefs-basic-panel
      * prefs-advanced-panel
      * etc
    * content
    * presentation
    * extensions

So in the administration branch of docs, the panel doc pages have URLs like this:

* /admin/ (index=default=users panel doc)
  * /admin/diagnostics-panel
* /content/ (index=default=write panel doc)
  * /content/pages-panel
* /content/links-panel
* /presentation/ (index=default=pages panel doc)
  * /presentation/styles-panel
* etc

That URL structure is intuitive because it more accurately reflects the UI organization. I.e., it's consistent and supporting the mental model people are learning about Txp's administration side.

Regarding file names, in case you're wondering, I feel file names are better in this case as "name-panel" because it's just more clear that something hyphenated is a file, not a folder, and they better indicate what the doc is about (e.g., /diagnostics-panel isn't just about diagnostics in general, it's about the **Diagnostic** panel, specifically). The distinction is subtle here, perhaps, but it makes more sense when you're writing about these things in copy and need to format labels and links differently than regular use of the same terms. (All that will be talked about in the style guide under "UI content" stuff.)

I'm guessing the folder structure was changed because of the breadcrumb links not working well? If true, then my position would be to not sacrifice the usability of URLs for the sake of the breadcrumb. I have an alternative idea about that, which I'll post in the other issue concerning breadcrumbs, #31

**Comment by philwareham** [comment]
It as more to do with avoiding deep links and lack of index pages (each directory will need an index file), but the breadcrumbs are also an issue (Jekyll just isn't capable of doing those easily - not without a plugin, which we can't run on GitHub's server).

If you are adamant you want that structure then please revert.

**Comment by wion** [comment]
We can avoid the index pages easy enough by not using them as file names or using links like "/admin". But I think the folder paths are worthwhile. So how about a compromise: folder paths but no index pages. :)

**Comment by wion** [comment]
After thinking about this more, Phil, putting all admin files in the "administration" folder probably won't impact usability even if it doesn't help it (a break even), so I'll go the direction you were headed. It will certainly make writing links easier.
