### ISSUE TITLE
Forum FAQs redirect

### ISSUE THREAD

**Issue by wion** [textpattern/textpattern.github.io#41]
The [FAQ forum category](http://textpattern.com/faq/?c=forum) and its three contained FAQs can all be 301ed to here...
http://forum.textpattern.com/help.php

Remove the "Forum" option from the "FAQ Categories" list too.

**Comment by philwareham** [comment]
I've got Monday morning free so I will look into this then. Cheers.

**Comment by philwareham** [comment]
Done.
