### ISSUE TITLE
All links should be full URLs (with domain name)

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern.github.io#43]
All links within the documentation should be full URLs, for example

```
http://docs.textpattern.com/tags/article-custom
```

This will allow for easier reuse of doc text within other projects (such as an e-book or pophelp files).

Also needs to be stated in the doc style guide.

**Comment by wion** [comment]
Okay. Thanks. I was wondering about that; kept going back and forth. Not
exactly pretty, or easy to read, but if it's required...

**Comment by wion** [comment]
What about the "On this page" intra-page links that go to page headings?
Does those need it too? Please don't say yes.

**Comment by philwareham** [comment]
No, I don't think we need to change those! :)

**Comment by petecooper** [comment]
Done, closing.

**Comment by philwareham** [comment]
Actually had a retina on this - so people can build and test locally we would make all internal URLs relative paths. Will open a new issue.
