### ISSUE TITLE
First login landing panel from last installation screen/step

### ISSUE THREAD

**Issue by wion** [textpattern/textpattern.github.io#44]
I need a reminder about what the default admin-side landing panel is if someone clicks the "Main interface" link in the "Step 4: Go!" screen of installation. Do they land on _Update languages_, like when updating an install, or is it Diagnostics? 

Ideally that first landing should be the Diagnostics panel -- thus coinciding with the suggestion made about diagnostics in the "Go!" screen.

**Comment by Bloke** [comment]
They hit the admin-side login screen.

**Comment by wion** [comment]
> I agree that Diagnostics makes sense on first install, as long as we can reliably detect that

Yeah, for the moment I'm focused on new installs. What do you mean by reliably detect it? Like whether it's a new install vs. an upgrade?

  > but [diagnostics is] not a very pretty landing page for complete newbies (mind you, nor is the Languages panel! They both violate the "Just Write" mantra by getting in the way before you can start writing). 

Yeah, but both, and especially diagnostics, is an essential part of the install/configure/troubleshoot process for any website and thus any person doing the install. So I don't think it matters that it's not pretty. Function over form, baby. Bootcamp. Security before comfort. Etc.

I might as well say that I posed this question first because I'm finishing up with the Installing Textpattern doc and I needed clarification to on landing panel to finish. 

But I'm inching towards proposing a number of copy changes for 4.6 (or whatever next version number is) with respect to the "new install" screens and post- first log in steps. I want to get the style guide finished up a bit more first for reference, but quickly it's going to be along these lines:

1. Some dialogue changes in the install screens. Not much, mainly some clarifications via better word choice/labeling.
2. A couple/few formatting changes, different from earlier incarnations of the style guide. Sorry. For example, all server paths and folder/file names should be formatted as italic, not code.
3. And then the real magic, again through content... harmonizing the UX between last install screen and post first–log-in steps, which means:
  1. Some screen copy edits to make clear that the admin should see the default (out-of-the-box) article when diagnostics are taken care of. (Thus why it's important to put them at diagnostics, if possible.)  
  2. The aforementioned article will be rewritten to provide more productive suggestions, which I've mostly finished writing now and will show when I get a few more pieces in place.

See [the last section of the install doc](http://docs.textpattern.io/installation/#sec4-5) now. It might help clarify the idea a bit. The only thing you don't see/know yet are the actual copy changes I'll propose, which are forthcoming. 

Btw, where would you like those copy-change suggestions when the time comes? Textpattern repo ticket? There will be two things:

1. Copy/formatting edits on the install screens.
2. A new default article for fresh installs. 

Maybe this docs repo is better, at least for the article copy, since it will be a little content-intensive... kind of like this post. ;)

**Comment by Bloke** [comment]
Docs are looking sweet. Nice work, Sir.

I don't know if there is a decent way to detect if someone has installed vs upgraded, because it runs the same code. Off the top of my head, it might be possible to make a note of the version number in the database immediately prior to running the upgrade scripts, so we could check to see if it's 1.0.0 (or whatever version number is in `txpsql.php`) then we'd know it was a from-scratch installation. Might be able to divert to a different screen then. Would have to test it.

Regarding copy changes in the code, it's likely to be a Textpack issue so raise an Issue there. And as you say, front side article content is best off in this repo I think.

**Comment by wion** [comment]
If it's a hassle to detect the first log in context, no big deal. We can just leave the doc as written, and make the first 'suggestion' in the default article about diagnostics, in case anyone got excited and skipped over that part. They'll get the message one side of the login or the other. ;)

Will do with directing issues.

**Comment by philwareham** [comment]
Textpattern 4.7 onwards lands in the diagnostics panel after install/upgrade - so the docs are OK as they currently are written, in that 'you should proceed to the diagnostics...' covers future releases and legacy ones. Closing, thanks.
