### ISSUE TITLE
[reminder] /files folder path/permissions warning for non Diagnostics access

### ISSUE THREAD

**Issue by wion** [textpattern/textpattern.github.io#46]
Note to self to come back to... 

When the path to the /files folder is wrong or not writable, and a user role can't see the **Diagnostics** panel (e.g., Designer), the warning is displayed to the user at the top of the relevant panel (e.g., **Files**).

Any other situations like this?

**Comment by Bloke** [comment]
I think the Images panel does the same sort of thing if the `/images` directory is not writable.

P.S. are we standardising on `folder` or `directory`, or does it depend on context? fwiw, I seem to recall the help system uses `directory`.

**Comment by wion** [comment]
> are we standardising on folder or directory, or does it depend on context?

This is a good question I've had many go-arounds with. In terms of a stiff rule, I don't think we can really make one. But I have tried to follow a pattern of use for myself where I use "directory" when referring to any preexisting and fixed location, whether system file tree (e.g., the /textpattern directory) or server (e.g., the /etc directory), but use "folder" when it's something a user needs to create or modify after the fact (e.g., change rights on the /files folder, delete the /setup folder, create a /plugins folder, whatever). I may not remember to always follow my divining wand rule, but I'm pretty sure nobody is confused by exchanging the terms here and there. When it comes down to it, it's really how monotonous sounding your copy is if you try sticking with just one term. If it's really stiff and robotic sounding with directory, directory, directory... then switch up once in a while to humanize it. I'm sure most people think "folder" is a friendlier term than directory, but a logical mix of both is probably ideal.

Two cents. I don't think we need a confusing rule for it.

**Comment by Bloke** [comment]
Makes sense. Variety is the spice of life and all that.

**Comment by wion** [comment]
> P.S. are we standardising on folder or directory, or does it depend on context? 

How about we aim for using 'directory' whenever possible, if it makes sense in the sentence and context. And if an instance of 'folder' slips in, or it just seems to work better, no big deal.

**Comment by wion** [comment]
Closing. I'll make a note about using 'Directory' in a Terminology section of the style guide.
