### ISSUE TITLE
Repo description

### ISSUE THREAD

**Issue by wion** [textpattern/textpattern.github.io#56]
Suggest changing the description on this repo to "Textpattern CMS user documentation" so it's absolutely clear. Never mind about "migrating" and "wiki" and whatever. Just make it focused on the product.

**Comment by philwareham** [comment]
Ok by me. I'm away this weekend on holiday but I'm gearing up for further developing this site now that Textpattern 4.6 release is out of the way.

**Comment by philwareham** [comment]
Done.
