### ISSUE TITLE
Plugin developer prefix registration

### ISSUE THREAD

**Issue by gas-kirito** [textpattern/textpattern.github.io#65]
Hello, I'm developing a new plugin for click-paste images in Write tab. I'm quite done with it. I would like to register the prefix `gas` so I can public this new plugin.

This is my profile on forum: [http://forum.textpattern.com/profile.php?id=201756](http://forum.textpattern.com/profile.php?id=201756)

Thank you.

**Comment by philwareham** [comment]
Sounds good. I'll reserve that prefix for you and add to the listing when next at a computer. Please kindly announce your plugin over at forum.textpattern.com when you are ready to show it off.

**Comment by gas-kirito** [comment]
Thank you. Just announced here:
[gas_img_popper: a new plugin for click-paste images in Write panel](http://forum.textpattern.com/viewtopic.php?id=47518)

**Comment by philwareham** [comment]
FYI I've added you to the prefixes list now.
