### ISSUE TITLE
Tag trace documentation

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern.github.io#66]
@Bloke @vanmelick @rwetzlmayr @petecooper @bloatware @makss

The tag trace FAQ in the old Wiki site was one of the most linked-to articles. That is now missing in the new site and will cause major link rot. Can someone who knows how this functions just write a small primer on it. Doesn't have to be much.

Here is the old text I've lifted from Google's cache:

```
Tag trace

In Debugging mode, Textpattern appends a Tag Trace to the HTML output of each page. This is your key to working out which Textpattern tags are being executed and their outcome.

View the HTML source of the page, and scroll to the bottom. The trace looks something like this:

[Page: default]
<txp:css/>
<txp:page_title/>
<txp:link_to_home>
	<txp:site_name/>
</txp:link_to_home>
<txp:site_slogan/>
<txp:linklist wraptag="p" />
	[SQL (0.000112): select Form from `txp_form` where name` = 'plainlinks' limit 1]
	[Form: plainlinks]
	[SQL (0.000153): select * from txp_link where 1 order by linksort ]
...

Some things to check:

* The lines [Page: default] and [Form: plainlinks] indicate that a particular Page template or Form has been loaded. Make sure it's the right one
* Is the code in question shown in the tag trace at all? If not, it might have been excluded by a conditional tag (<txp:if_...>).
* If the problem code is in an article form, link form or comment form, is it being loaded? There might not be any articles/links/comments to display at all. The SQL query for the preceeding tag might give you a hint.
* If you can't fathom it out, post the relevant parts of the tag trace in a new topic on the Forum along with a description of the problem or what you expect to see, and someone will endeavour to help you out.

**Comment by Bloke** [comment]
Can't we just tidy up [this doc](https://github.com/textpattern/textpattern.github.io/blob/master/faqs/tag_trace.md) which seems to be the same as you posted?

imo, once the remaining FAQs have been assimilated into the proper documentation, the (few) remaining true FAQs can just appear as a list in the FAQ section. No need for the subcats.

What might be better still, is to roll every single current FAQ into the documentation context, effectively emptying the FAQ section. Then curate a bunch of endpoints into a single index.md page - like we do with [the main page](https://github.com/textpattern/textpattern.github.io/blob/master/index.md) - with appropriate titles like "How do I use a Tag Trace?" which points to the actual doc area that contains the answer to that question.

Saves resource, and any alterations can just be added/removed in that index over time.

**Comment by philwareham** [comment]
Well, I need you to decide whether that doc stays as a FAQ or is put somewhere else (and if it needs to be updated due to the expanded tag trace I believe has been implemented).

What I'm basically saying is, this document needs to be a priority to be put live as it has a lot in inbound links. the longer it stays offline the bigger the rot.

**Comment by philwareham** [comment]
Also, I agree on the reduced FAQ - just needs someone to do it that isn't me. I'll remove the categories there in the meantime.

**Comment by Bloke** [comment]
Gotcha. I'll try and find a slot for it in the docs later tonight and set the `index.md` in the FAQ section to at least link to it.

**Comment by Bloke** [comment]
Update Tag Trace links to point to http://docs.textpattern.io/installation/troubleshooting-textpattern#the-tag-trace

**Comment by philwareham** [comment]
Cheers dude, I have now 301 redirected the old wiki link.
