### ISSUE TITLE
Evaluate tag document needs writing

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern.github.io#68]
@bloke @bloatware this document needs some text and examples: http://docs.textpattern.io/tags/evaluate

I'd really like to use the `txp:evaluate` but I'm confused about how it works fully and tests things at the moment.

**Comment by bloatware** [comment]
Sorry, `hide` and `evaluate` are not yet feature-stable. I would like to implement @makss `secondpass` parse proposal, but am not sure in which one, if either.

**Comment by philwareham** [comment]
OK, no worries. I'll keep the issue open for when it's stable.

**Comment by philwareham** [comment]
Done. Closing.
