### ISSUE TITLE
Is it "posted desc" or "Posted desc"?

### ISSUE THREAD

**Issue by joopvos** [textpattern/textpattern.github.io#74]
It seems that it has to be "Posted desc" to get the sort attribute working. The first letter has to be capitalized. The docs are a little inconsistent or at least confusing. E.g. > [docs.textpattern.io/tags/article](https://docs.textpattern.io/tags/article)

**Comment by philwareham** [comment]
Thanks for the report. @Bloke @bloatware is this correct? If so the attributes should really be case insensitive yes?

**Comment by bloatware** [comment]
Some servers (Windows?) are case sensitive, some are not. We'd better keep to exact matches.

**Comment by philwareham** [comment]
OK, I'll amend the docs.

**Comment by philwareham** [comment]
So... would all the sort values to capitalised? i.e. `Section desc`, `Authorid asc`?

**Comment by bloatware** [comment]
Unfortunately, there seems to be no general naming convention in txp db. We have `Section`, but also `description`, `AuthorID`, `LastMod`, `comments_count` and so on. Since `sort` attribute uses raw SQL, you'll need to check the fields names table by table. And I don't see how this could be amended without breaking the bw compatibility...

**Comment by philwareham** [comment]
OK, I've checked the table columns in the whole system and amended docs accordingly. Horribly inconsistent, but we can blame previous devs for that illogical mess.

**Comment by joopvos** [comment]
... and what about 'Posted asc' ... !? ... it's not on the list.

**Comment by philwareham** [comment]
Well, `asc` and `desc` are a separate topic since they are not specifically referencing the database table columns. But I agree there should be some mention of what they do (the content was taken from the old wiki and it seems these were never mentioned there. Leave it with me.

**Comment by philwareham** [comment]
OK, done!

**Comment by joopvos** [comment]
:)
