### ISSUE TITLE
4.7 tag changes for documentation

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern.github.io#75]
This is the place to put reminders of tags that have had changes in functionality since 4.6:

* [x] short tags are now supported and need documenting (e.g. `<tag:: ...`).
* [x] valueless attributes? Need to clarify what this changes is?
* [x] changed: `txp:page_title` tag SEO - site name renders after page name, default separator changed from ` : `' to ` | `, page numbers added.
* [x] Deprecated the `poplink` attribute on `txp:thumbnail` tag.
* [x] `txp:hide` tag has new attribute to document `process`.
* [x] `txp:page_url` tag has new attribute `default` and possibly changes to `type` attribute behaviour.
* [x] `txp:article_custom` tag can count pages.
* [x] Deprecated `txp:image_display` and `txp:image_index` tags, use `txp:image` and `txp:images`, respectively, instead.
* [x] `txp:breadcrumb` can be used as a container tag.
* [x] `txp:image_author` tag now accepts `id` and `name` attributes.
* [x] `txp:output_form` accepts a range of user-defined attributes.
* [x] `txp:yield` tag has new attribute to document `default`.
* [x] `escape` attribute values.
* [x] `process` global attribute <del>needs to be documented fully and example uses given</del> is called `txp-process` now. It is intended for internal use and shouldn't be officially introduced atm (subject to change).
* [x] These are global attributes: `breakby`, `breakclass`, `class`, `escape`, `html_id`, `not` and `wraptag`.
* [x] Add `txp:if_logged_in` docs (https://github.com/textpattern/textpattern.github.io/issues/93)

**Comment by petecooper** [comment]
- [ ] Sanity check and overhaul Themes docs (see https://github.com/textpattern/textpattern/issues/1111#issuecomment-357238440)

**Comment by petecooper** [comment]
All clear/done at time of writing. Great work, dudes!

**Comment by philwareham** [comment]
Thanks Pete. Closing. If other changes reveal themselves later we can handle one at a time.
