### ISSUE TITLE
page: Configuring a web server for Textpattern

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern.github.io#76]
NGINX support has been added in 4.7. Documentation will need to be written at launch. Reference material here: https://github.com/textpattern/textpattern/pull/910.

**Comment by petecooper** [comment]
Right, I've spent some time working out some Nginx stuff, and it's fairly straightforward.

I'll assign myself to this for now, though I'm not precious about it if someone else wants to take a shot.

**Comment by petecooper** [comment]
See also https://github.com/textpattern/pophelp/issues/38

**Comment by petecooper** [comment]
I'll take a crack at this tonight after yoga. The general install doc needs some overhauling, too.

**Comment by petecooper** [comment]
OK, I've reworked https://github.com/textpattern/textpattern.github.io/blob/master/installation/installing-textpattern.md a fair bit and I need to think on the best approach from here. I am aware of https://github.com/textpattern/textpattern.github.io/blob/master/installation/installing-on-an-nginx-webserver.md – it's likely to be superseded by a more server agnostic doc, perhaps along the lines of "Web server software considerations", which gives scope for other, perhaps not officially supported routes on things like [Caddy](https://caddyserver.com), etc.

**Comment by petecooper** [comment]
RFC here: https://forum.textpattern.io/viewtopic.php?id=48269

**Comment by philwareham** [comment]
Thanks Pete. I'll review that Nginx doc in due course and link it up somewhere. Agree that in future we should have further info on other server types if compatible.

**Comment by petecooper** [comment]
I've been mulling for a while, having read that linked NGINX doc (from, 2011-ish) and I'm coming down on the side of having a single, long article with hyperlinked sections per web server, supported ones first and so forth. That would then mean the NGINX-specific doc would be able to be retired in favour of something more scalable.

I'll start drafting something and you can pick holes etc.

**Comment by petecooper** [comment]
Can probably be closed, pending review and publication.

**Comment by philwareham** [comment]
It's live but needs peer review (and syntax highlighting amend - note to self: does Prism have nginxconf syntax)

https://docs.textpattern.io/installation/configuring-a-web-server-for-textpattern

**Comment by petecooper** [comment]
@philwareham Prism with nginxconf (gist): https://gist.github.com/misiek08/6566480

**Comment by petecooper** [comment]
FWIW, I've battle-tested it on a few Nginx sites, seems to work fine.

**Comment by philwareham** [comment]
I've added Nginx syntax highlighting now. Closing this issue as everything else was already done. Thanks Pete!

**Comment by philwareham** [comment]
Sorry, @petecooper - what docs should I keep (or should I keep both)?

https://docs.textpattern.io/installation/configuring-a-web-server-for-textpattern

https://docs.textpattern.io/installation/installing-on-an-nginx-webserver

**Comment by petecooper** [comment]
@philwareham - keep both for now, please. When I find some time I'll merge the Nginx specifics into the configuring doc and retire the Nginx one.

**Comment by wion** [comment]
Just bringing the issue subject into conformance with developing procedures. ;)
I chose that page title as it looks like the one Pete will align to.

**Comment by petecooper** [comment]
Closed for now, nothing in the legacy doc that's broad enough for general adoption that wasn't already covered in the main doc, so done.

**Comment by wion** [comment]
https://github.com/textpattern/textpattern.github.io/commit/3763416be52714cf35b3b2b598f7d35a1d82f7bc
