### ISSUE TITLE
Jekyll build has started failing

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern.github.io#77]
Not sure why - will investigate sometime this week.

Was building fine as of 2nd August 2017 - failed as of 11th August 2017. Commit on 11th had no breaking code so must be something in the Jekyll release that has changed.

For reference:
https://help.github.com/articles/viewing-jekyll-build-error-messages/
https://help.github.com/articles/generic-jekyll-build-failures/

**Comment by petecooper** [comment]
I've got some time to kill this evening, I will have a look.

@philwareham - any chance I can have access to Settings so I can view the build errors?

PS: it's 2017, not 2018 in your OP.

**Comment by philwareham** [comment]
Thanks Pete (also I've come back from the future now and changed the dates)

**Comment by petecooper** [comment]
I think I need to be a Member of the repo to be able to see the build errors (accessed via Settings, which I can't see because I'm not a member).

**Comment by philwareham** [comment]
There’s no build error message apart from the generic ‘failed to build’. So I’m unsure what is causing it. Will probably have to run a local Jekyll install and see if I can build or not.

**Comment by petecooper** [comment]
I'm building a local Jekyll now, keep you posted.

**Comment by petecooper** [comment]
Our survey says…:

```
$ bundle exec jekyll serve
Configuration file: /home/pi/repo/textpattern.github.io/_config.yml
       Deprecation: The 'gems' configuration option has been renamed to 'plugins'. Please update your config file accordingly.
            Source: /home/pi/repo/textpattern.github.io
       Destination: /home/pi/repo/textpattern.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
    Liquid Warning: Liquid syntax error (line 5): Expected id but found open_square in "item in site.[item.label]" in feeds/feed.json
  Liquid Exception: nil is not a symbol in feeds/feed.json
jekyll 3.5.1 | Error:  nil is not a symbol
```

**Comment by philwareham** [comment]
Thanks Pete - I've got Jekyll to build again now thanks to your work! 👏👏👏
