### ISSUE TITLE
Investigate automatic compilation of docs to offline format

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern.github.io#79]
R&D phase.

**Comment by philwareham** [comment]
Adobe Acrobat DC (which I have as part of Creative Cloud) can turn an entire site into a PDF. Just giving it a try now. Looks like it'll need some cleanup but in principle it works - will post a scrappy copy here when finished compiling.

**Comment by Bloke** [comment]
@philwareham Oooh nice.

@petecooper If you're tempted to flex your scripting muscles using `sed` or `awk` then watch out for the [caveats of doing a recursive find in a git repo](https://stackoverflow.com/questions/1583219/how-to-do-a-recursive-find-replace-of-a-string-with-awk-or-sed). Basically, omit the `.git` directory and hidden files or things could go bad very quickly!

**Comment by philwareham** [comment]
Yeah, Acrobat was pretty crappy - back to the drawing board on this.

**Comment by petecooper** [comment]
Thanks, dudes - appreciate your input on this.

**Comment by petecooper** [comment]
merging into https://github.com/textpattern/textpattern.github.io/issues/162 to reduce noise
