### ISSUE TITLE
Admin page references

### ISSUE THREAD

**Issue by wion** [textpattern/textpattern.github.io#81]
It's been a while since giving docs any attention (sorry), and it could have been my suggestion originally to belabor clarification of admin panels (perhaps too much wine), but...

I was just noticing references to admin panels... Using the Write panel here as example, I see the references written like "Write administration panel", instead of simply the "Write panel". 

In context of an admin-side page doc, this is completely unnecessary because the context already makes the "administration" part obvious. But I would argue it's not needed in the other doc pages either since there is no such thing as "panels" by any other context than the admin-side.

So, don't bust your humps making back edits, but next time you edit a relevant page, drop the needless "administration" part from the references.

2 cents.

**Comment by philwareham** [comment]
Sure, I can search/replace those easily. I'll do that now.

Cheers!

**Comment by philwareham** [comment]
Done! 😀
