### ISSUE TITLE
The valuable Write panel bug

### ISSUE THREAD

**Issue by wion** [textpattern/textpattern.github.io#82]
I edited the Write panel doc a bit ago, adding a tip under the **Custom fields** section in relation to isolating the ID value of an image in the **Article image** field.

Bloke pointed out it's a (useful) bug...
https://forum.textpattern.io/viewtopic.php?pid=307670#p307670

I would argue it's useful enough to doc as I've done, at least until the bug is ever fixed or a core solution materializes to grab the raw ID value from the images field.

**Comment by philwareham** [comment]
Great, thanks Destry. Looks fine to me.

**Comment by wion** [comment]
Improvements needed, based on discussion in the thread.

**Comment by wion** [comment]
I've opted to remove mention of the useful "custom field" bug entirely and just highlight a tip under the **Article image** section of the Write panel doc about how to isolate the ID with tags other than the `article_image` tag. I think that's useful there, and it recycles the markup example used previously, but with a lean on the short-form notation of writing it.

**Comment by wion** [comment]
@Bloke has been following the associated forum thread, so if I've fudged anything up in meaning, he might be quick to spot it.
