### ISSUE TITLE
Header tag document needs writing

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern.github.io#83]
There is another new tag to be documented when Textpattern 4.7 is release.

    <txp:header />

Info and examples needed.

**Comment by wion** [comment]
I assigned a tag so I could follow along. ;)

Can we edit the draft in this thread? Or is there a dedicated place for such?

I'm curious to learn how this will work. Maybe we can hashout a couple of the examples here?

**Comment by philwareham** [comment]
@bloatware added that tag. To be honest I didn't even know it existed until I saw it mentioned in the `HISTORY.txt` file. I'm also keen on seeing what this tag can do.

**Comment by bloatware** [comment]
It allows power (i.e. `<txp:php />`-able) users to set [HTTP headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers). Try this in some page form:
```
<txp:header name="Content-Type" value="application/json" />
```
and the page will serve its content as JSON. You'll need to ensure its validity, of course. The kind of things we do with `rah_external_output`.

**Comment by wion** [comment]
Thanks! 

Non-power user out. ;)

**Comment by bloatware** [comment]
To give another example, suppose that you don't want the articles from some section be cached by the browser. Then the corresponding page template could contain
```
<txp:header name="Cache-Control" value="no-cache, no-store, must-revalidate" />
```
Yes, it's mainly for admins.

**Comment by bloatware** [comment]
Done, though a gentle warning "you know what you are doing" wouldn't hurt.

**Comment by philwareham** [comment]
Thanks. Just doing some editorial work on that doc. Does `replace="boolean"` accept the common `0` (no) or `1` (yes) values? You've put `Default: true` in the doc.

**Comment by bloatware** [comment]
Yes, `boolean` in Textpattern means "empty or not", so `Default: "1"` will be ok too.
