### ISSUE TITLE
New "short-form vs. long-form" doc

### ISSUE THREAD

**Issue by wion** [textpattern/textpattern.github.io#84]
I've added a new doc under the *Tag Basics* section that focuses on a concept that hasn't had much direct explanation before: writing Txp tags markup in short-form vs. long-form notation.

I think this would be useful for new learners, which is who I consider official Txp documentation being for. 

The link is here...
https://docs.textpattern.io/tags/tag-basics/shortform-vs-longform-usage

The entire integration of the doc could use a second pair of eyes to find any gotchas.

Thanks.

**Comment by philwareham** [comment]
Thanks Destry - I'll try to proof read it within next day.
