### ISSUE TITLE
Homepage "Core tags" list

### ISSUE THREAD

**Issue by wion** [textpattern/textpattern.github.io#86]
The "Tags basics" item has one nested item under it, but there are in fact 6 items under tag basics. Seems a little lopsided. I'd say they should all be there or none. All is probably more usable.

I can change it if there's no objections.

**Comment by philwareham** [comment]
Probably remove the sub-section then, thanks. If we add all it's going to 'snow-blind' people I think.

**Comment by wion** [comment]
Maybe something like this instead...

* [Tags reference](https://docs.textpattern.io/tags/) (the complete book of tag magic)
* [Tag use basics](https://docs.textpattern.io/tags/tag-basics/). Six essential docs to wizard-level skills, including:
  * [Parsing tag attributes](https://docs.textpattern.io/tags/tag-basics/parsing-tag-attributes) (er, sorcery)
* [Tags in development](https://docs.textpattern.io/tags/tags-in-development) (incantations to come)

It spices it up a touch and invites investigation, plus indicates there's more than one basics doc to see.

**Comment by wion** [comment]
Done.
