### ISSUE TITLE
Core callbacks reference is a mess

### ISSUE THREAD

**Issue by kuopassa** [textpattern/textpattern.github.io#87]
[This page](https://docs.textpattern.io/development/core-callbacks-reference) would be more useful if content would be beautified a bit.

**Comment by philwareham** [comment]
That page is a TODO - i.e. it has been formatted properly in Markdown yet.

**Comment by philwareham** [comment]
It will get done eventually but I have to pick my battles wisely and this one is low priority for me right now. Of curse anyone is free to today it up.

**Comment by Bloke** [comment]
I started tidying it ages ago, got partway through and got sidetracked by something else.

**Comment by wion** [comment]
It looks like someone cleaned it up. Can we close this?

**Comment by philwareham** [comment]
Yep!

**Comment by bloatware** [comment]
Sorry, I have introduced an experimental feed (rss/atom) callback in 4.7.2 to be able to filter feeds articles (say, only sticky). Will document it when ready.
