### ISSUE TITLE
URLs don't match search terms after first search

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern.github.io#89]
* Visit https://docs.textpattern.io
* Use the search bar to search for something (example: `requirements`)
* Note search results page and search stub + query (example: `/search/?q=requirements`)
* Use the search bar to search for something different (example: `system requirements`)
* Note updated search results and _previous_ search query (example: `/search/?q=requirements`)

Safe for work video attached, no commentary.

[search query.zip](https://github.com/textpattern/textpattern.github.io/files/1599008/search.query.zip)

**Comment by bloatware** [comment]
Most probably the effect of AJAX refresh, `window.history.replaceState` should fix it.

**Comment by philwareham** [comment]
Sorry, my JavaScript knowledge is pretty shit. I have no idea how to fix this. Maybe someone else can amend it to work as expected (the whole search feature is basically borrowed code from here https://github.com/mathaywarduk/jekyll-search since vanilla Jekyll doesn't read have a search function).

**Comment by bloatware** [comment]
Sure, I can take a look if I have a sufficient access, will check.

**Comment by bloatware** [comment]
I've made an [attempt](https://github.com/textpattern/textpattern.github.io/commit/ffdc86d5c385dd901fead4c422055678196fb8ce), but one needs to modify the minified version to get it working. Don't wanna do it by hands...

**Comment by petecooper** [comment]
Thank you @bloatware - I've minified `search.js`.

**Comment by petecooper** [comment]
Fixed! Works perfectly! Thanks again @bloatware - much better.

[89.mp4.zip](https://github.com/textpattern/textpattern.github.io/files/1616196/89.mp4.zip)

**Comment by philwareham** [comment]
Cheers Oleg!
