### ISSUE TITLE
page_url tag has new options

### ISSUE THREAD

**Issue by Bloke** [textpattern/textpattern.github.io#90]
See [this post](https://forum.textpattern.io/viewtopic.php?pid=308610#p308610) for details.

**Comment by petecooper** [comment]
Done.

**Comment by philwareham** [comment]
Thanks! Probably would be beneficial to have at least one example of the new behaviour too, though.

**Comment by petecooper** [comment]
Agreed. I'll make some soup and take a look.

**Comment by petecooper** [comment]
Done via https://github.com/textpattern/textpattern.github.io/commit/ca127f249acca0615286b4d66aeb47ab41257b0d

(And I didn't have soup.)

**Comment by philwareham** [comment]
I did have soup. Thanks Pete!
