### ISSUE TITLE
Multi-site document URL is 404

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern.github.io#96]
https://github.com/textpattern/textpattern/blob/dev/sites/README.txt#L10 refers to https://docs.textpattern.io/installation/multi-site-textpattern, which is currently 404.

I can't locate the instructions @jools-r wrote, any clues as to where that ended up?

**Comment by Bloke** [comment]
Hmmm, was this just a placeholder that never got made?

Can we [cadge anything from this post](https://forum.textpattern.io/viewtopic.php?pid=308038#p308038) to make the doc at least go somewhere?

**Comment by jools-r** [comment]
My instructions are [here](https://github.com/jools-r/textpattern.github.io/blob/5565d47a86eb4b021298437d4a89fab526e802b6/installation/multi-site-textpattern.md) and it's just waiting on my [pull request](https://github.com/textpattern/textpattern.github.io/pull/92) on the docs site to be accepted. I had two todos there, but neither are essential. They're just for the sake of completeness.

**Comment by Bloke** [comment]
We could merge that now. Close enough to launch of 4.7. proper that it'll make little difference, but we can always make a note in the header of the article that it only applies from 4.7 onwards. Should we retain the old docs for pre-4.7.0 somewhere? Or have we taken the stance that the docs only reflect "now"? Can't remember...

**Comment by philwareham** [comment]
Docs reflect now generally, but should mention that 'From Textpattern CMS 4.7 onwards...' for clarity. I've merged that multi-site doc but feel free to add/amend where necessary. @jools-r if you want commit access to this docs site then let me know. Cheers!

**Comment by petecooper** [comment]
OP resolved, closing.
