### ISSUE TITLE
CSP document

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern.github.io#99]
As we have plans to [improve CSP requirements](https://github.com/textpattern/textpattern/issues/1142) (is that the right word?), I am in favour of a CSP statement of intent, perhaps to merge into system requirements when the time is right.

Is this in-scope for the project? Not necessarily right now, but at a suitable time in the future.

**Comment by Bloke** [comment]
Sounds reasonable to me.

**Comment by philwareham** [comment]
Yep, agreed. When the snagging list of 4.7.x stuff is done we can give some energy to changes in 4.8 development. I will also need your knowledge of Nginx Pete when we come to tackle CSP items.

**Comment by petecooper** [comment]
Right, we're off the blocks: https://github.com/textpattern/textpattern.github.io/blob/master/installation/content-security-policy.md

WIP at the moment, use appropriate kid gloves etc.

**Comment by petecooper** [comment]
Gonna close this as we have something to work with.
